### ISSUE TITLE
How to create the navigation bar?

### ISSUE THREAD

**Issue by hrysakis** [thaider/Tweeki#106]
Hello as a newbie in mediawiki I have already installed thweeki skin.

However, the default navigation bar (menu) is not appeared as it is depicted in the respective skins url: https://tweeki.thai-land.at/wiki/Welcome

How can I figured it out?

Thanks in advance.
Giannis.

**Comment by thaider** [comment]
Hi. 

Sorry that the documentation is not very newbie-friendly. Tweeki's menus are configured via system messages. You can overwrite the default messages by creating pages in the MediaWiki namespace. To customize the navbar you can create the `MediaWiki:Tweeki-navbar-left` and `MediaWiki:Tweeki-navbar-right` pages. You can add items using [Button Syntax](https://tweeki.thai-land.at/wiki/Buttons), e.g. write `Some Page` to create a link to a page with that title. 

If you want dropdowns, use `*` for the sub-items. 

There's also a bunch of special [navigational elements](https://tweeki.thai-land.at/wiki/Navigation) that you can use, e.g. `SEARCH` to create a search box.

Hope, this helps!

**Comment by hrysakis** [comment]
Dear @thaider 

Thanks for your reply. I need more some kind of help. I have created the page[1]: http://localhost/mediawiki/index.php?title=MediaWiki:Tweeki-navbar-right and put the following sample code:
<btn>
Dropdown-Menu-right
*Menu Item1
*Menu Item2
*Menu Item3
</btn>

[1] I followed the process of creating a page by searching the name ( MediaWiki:Tweeki-navbar-right)and then click to edit to enter the above code.

The dropdown has been apperead on the left but I can see also the <btn>...</btn> tags. What I'm doing wrong?
Thanks again for your help.

**Comment by thaider** [comment]
I'm not sure I get you right. Could you please provide a screenshot so I can better understand the problem?

**Comment by hrysakis** [comment]
Yes of course, you can look at the: https://ibb.co/iVoZvx

**Comment by thaider** [comment]
You don't need the `<btn>` tag in navigational sections. Also, the special navigational elements are case sensitiv, so it should be `SEARCH` instead of `search`.

**Comment by hrysakis** [comment]
Thanks for your help. Now it works!
