### ISSUE TITLE
is there someway I can put a block of text in the sidebar-right instead of having the edit button?

### ISSUE THREAD

**Issue by zhangx20** [thaider/Tweeki#112]

**Comment by thaider** [comment]
see [this newly added paragraph in the documentation](https://tweeki.thai-land.at/wiki/How-Tos#Show_a_text_block_in_a_navigational_section)

**Comment by zhangx20** [comment]
thank you! Is there some way I can customize the text? I want to bold certain parts.

**Comment by zhangx20** [comment]
thank you! Is there someway I can customize the right side bar so that only the TOC appears on one page and only MYNAV appears on another?
