### ISSUE TITLE
Anyone interested in working with a UX designer on this?

### ISSUE THREAD

**Issue by paulblochdesign** [thaider/Tweeki#117]
Hi All,
I'm wondering if anyone here would be interested in combining efforts to make some UX/design mods to Tweeki. I'm a designer and currently trying to adapt tweeki to a wiki project. There's a lot of great things I like about Tweeki but I'd also like to make some mods and perhaps work with someone invested in the project (I'm not a very good coder) to either add them here or create a new fork. I think that it would be fairly simple to make the "Medium.com" of mediawiki based on Tweeki and resolve many of mediawiki's longstanding design issues with it's default skins. I'd be open to working on the design within sketch and work with a dev(s) to discuss the UX and convert them.

Any takers? @djflux?

**Comment by djflux** [comment]
I'm just working on Tweeki for an internal work project. I can try to assist however my "free time" is limited so my contributions would depend on personal time commitments.

Let me know your thoughts.

Cheers,
Flux

**Comment by thaider** [comment]
Sounds interesting. Could you elaborate a bit on what exactly you would like to do?

**Comment by paulblochdesign** [comment]
@djflux @thaider 
Here's a few screenshots of what I've been working on. I think moving some Nav items is critical, batching controls of an article in the page rather than in the nav. All of them can basically remain hidden as editing isn't the most common feature of an article, reading it is. There could also be some "beautifiers" added as extensions such as a dropcap tag, adding a cover image, etc. (see the attached images). By default I'd also remove the "Main page" title on the main page. Just a few of many ideas. 

<img width="507" alt="screen shot 2018-06-03 at 1 36 29 pm" src="https://user-images.githubusercontent.com/35141616/40890986-465fd690-6733-11e8-95ed-bdd52f8e5c5b.png">
<img width="383" alt="screen shot 2018-06-03 at 1 35 59 pm" src="https://user-images.githubusercontent.com/35141616/40890987-46788082-6733-11e8-9b58-328799f8bf92.png">
<img width="929" alt="screen shot 2018-06-03 at 1 35 09 pm" src="https://user-images.githubusercontent.com/35141616/40890988-46902034-6733-11e8-8aaf-26512d0507aa.png">
<img width="934" alt="screen shot 2018-06-03 at 1 34 07 pm" src="https://user-images.githubusercontent.com/35141616/40890989-46a77b26-6733-11e8-9f8b-ff0447db910c.png">

**Comment by paulblochdesign** [comment]
What do you think? These are just mocks with some ideas. I think they need to be further refined but I'm curious what your impression is (and sense of feasibility). @djflux @thaider

**Comment by thaider** [comment]
I like it. I won't be able to support you more than with casual advice but it seems certainly feasible and if you manage to build it in a way that doesn't interfere with Tweeki's base I'd happily include it as a kind of optional theme.

**Comment by jcklpe** [comment]
@paulblochdesign  I'm also a UX Designer and I'm learning to code. I am taking a crack at using this skin as a starter template to make my own. Biggest problem I've had with skinning media wiki is how weird the skins are formatted and stuff compared to wordpress or other website/cms things that I've learned. If I can I'd love to have your feedback. I'll be sure to link my project page once I get it up. Still having trouble getting tweeki to properly display on my wiki right now.

**Comment by J4bbi** [comment]
Hey @paulblochdesign

How is your project going? 

I might be interested

**Comment by paulblochdesign** [comment]
Hey, sorry I missed this message. Are you still interested?

**Comment by paulblochdesign** [comment]
Hey, how'd your theme turn out? I haven't been monitoring github so I
missed this message. I'd be happy to take a look at your project.
