### ISSUE TITLE
problem with Right to Left languages

### ISSUE THREAD

**Issue by aso-mehmudi** [thaider/Tweeki#120]
Thanks for your great skin! Chameleon skin does not support Right to Left languages, but Tweeki does it well.
But there is a Problem with rtl in Tweeki:
Label for sidebar button for "page edit" in rtl language is still "Edit" but goes to "page watch"! 
how to fix this?

**Comment by aso-mehmudi** [comment]
Problem Solved!
please remove this if statement: Line 190 to line 198
https://github.com/thaider/Tweeki/blob/master/Tweeki.skin.php#L191

navigation elements  automatically reversed by css when UI is in RTL mode.
Thanks.

**Comment by thaider** [comment]
thank you!
