### ISSUE TITLE
http://tweeki.thai-land.at often unavailable

### ISSUE THREAD

**Issue by ser** [thaider/Tweeki#123]
http://tweeki.thai-land.at service is often offline, maybe it would be useful to have manuals copies available elsewhere as well?

**Comment by techrocket** [comment]
+1

**Comment by maxnth** [comment]
+1

**Comment by thaider** [comment]
Sorry for that, I'll try to fix a more reliable home for the documentation…

**Comment by thaider** [comment]
the documentation finally is on a new server that should be more stable. the URL changed already a while ago to https://tweeki.kollabor.at
