### ISSUE TITLE
MW1.32.0: toctogglespan is not handled correctly.

### ISSUE THREAD

**Issue by ajquick** [thaider/Tweeki#126]
A new addition to MW 1.32.0+ is "toctogglespan" which I believe is related to some kind of hiding the table of contents, or highlighting what content you are looking at? I'm not sure, but I do know it provides for a poor looking table of contents while using Tweeki.

The code was introduced here:

https://github.com/wikimedia/mediawiki/commit/56d45558b102349f3480a46819669407aa3be2d6#diff-8ffbd08183616445af94793926721964

A simple fix is to disable the display of the class in _MediaWiki:Tweeki.css_:

`.toctogglespan{
display:none;
}`

**Comment by thaider** [comment]
Hi. Thanks for reporting. Could you please provide a screenshot of how it looks like?

**Comment by ajquick** [comment]
![Here is an image showing how it looks in 1.32.0+](https://user-images.githubusercontent.com/6588235/51807960-c6381800-224a-11e9-9900-1fed400959f5.jpg)

**Comment by thaider** [comment]
Thanks for investigating this, hope it works…
