### ISSUE TITLE
Font-Weights not Rendered Correctly

### ISSUE THREAD

**Issue by ajquick** [thaider/Tweeki#127]
Due to a general lack of existing _Font-Weights_ in the provided font families, bold / bolder fonts are not displayed correctly. This can be demonstrated on the Tweeki Wiki, see the attached photos.

By removing the non-working bold font-weights (600,700), the problem is fixed and the page looks much better! This can be fixed by adding the following to _MediaWiki:Tweeki.css_

`.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6, .firstHeading, .tweekiFirstHeading, #tweekiTOC #toctitle h2, #tweekiTOC .toctitle h2 {
    font-weight: 500;
}`

Broken CSS:

![tweeki-bold-1](https://user-images.githubusercontent.com/6588235/51363711-8dec4900-1a96-11e9-8eea-4d3132658672.jpg)

Fixed CSS:

![tweeki-bold-2](https://user-images.githubusercontent.com/6588235/51363714-90e73980-1a96-11e9-94bf-c405e507926e.jpg)

**Comment by thaider** [comment]
Thanks! This is strange. I just tried it with the browsers on my current machine (Firefox and Chromium) and it's exactly the other way round. bold/600/700 works as intended, 500 doesn't. What browser and OS are you using?

**Comment by ajquick** [comment]
Latest version of Chrome and Win 10.

I believe this comes down directly to what system fonts are installed and how the CSS looks at the back up fonts before giving up and displaying it as a non-bold font. Perhaps you have a version of a font installed that I do not.

The best way to go about this, I believe is to include the fonts that you intend to use including the weights through a Google fonts file or some other means. Relying on Helvetica to be installed on the end user's machine for example may not be the best thing to do.

**Comment by thaider** [comment]
Agreed that in order to have better control the best thing would be to include your own web fonts. For Tweeki I'm going to stick with Bootstrap's choice of not including a default web font. As an admin you can always include the specific fonts that you would like to use...

**Comment by ajquick** [comment]
I know Tweeki is using Bootstrap 3, but in Boostrap 4 they have moved away from their choice of fonts. See their typography page which explains the changes: https://getbootstrap.com/docs/4.1/content/reboot/#native-font-stack

This article actually outlines a method for using built in system fonts for everything, which makes a lot of sense: https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/

They would recommend using the following CSS:

`font-family: -apple-system, BlinkMacSystemFont,
    “Segoe UI”, “Roboto”, “Oxygen”, “Ubuntu”, “Cantarell”,
    “Fira Sans”, “Droid Sans”, “Helvetica Neue”,
    sans-serif;`

**Comment by ajquick** [comment]
The exact reason it looked wrong on my computer was that I had Helvetica Neue installed on my computer, but not all font weights. So that makes sense!

**Comment by thaider** [comment]
Thanks for investigating this further. We're working on making BS4 available in Tweeki so this will solve the issue and I won't make any changes for now…
