### ISSUE TITLE
Anything before a colon in the page title is assumed to be a namespace, even if there is no such namespace

### ISSUE THREAD

**Issue by RibShark** [thaider/Tweeki#129]
When rendering a page that has a colon in the title, the page title heading is shown as if the text before the colon is a namespace, even if no such namespace exists:
![image](https://user-images.githubusercontent.com/1957489/51641521-449c6d80-1f5e-11e9-98fc-45b2628cfc34.png)

**Comment by RibShark** [comment]
Additionally, it seems after creating a namespace the text is rendered as if it was not one (all bold, no <span> in the header).

**Comment by RibShark** [comment]
Made a pull request to fix the issue: https://github.com/thaider/Tweeki/pull/130

**Comment by thaider** [comment]
Thanks for the fix!
