### ISSUE TITLE
Undefined property: SkinTweeki::$getUser MW1.32.0

### ISSUE THREAD

**Issue by Sparc0** [thaider/Tweeki#131]
Getting following error in my Nginx logs after i updated to latest MW1.32.0 release.
Using PHP7.2.

The only thing i can see on the page is the navbar.

I have edited navbar-left/right.
And i have the following stuff in my LocalSettings.php
```
#Tweeki
$wgTweekiSkinHideAnon['EDIT-EXT'] = true;
$wgTweekiSkinHideNonAdvanced = array( 'EDIT-EXT-special' => false );
$wgTweekiSkinHideLoggedin = array( 'footer-custom' => false );
$wgTweekiSkinUseBootstrapTheme = true;
$wgTweekiSkinFooterIcons = true;
$wgTweekiSkinUseAwesome = true;
```

**Nginx error log**
```
PHP message: PHP Notice:  Undefined property: SkinTweeki::$getUser in /var/www/wiki/skins/Tweeki/includes/TweekiTemplate.php on line 937
PHP message: PHP Notice:  Found alias defined for Userlogin when searching for special page aliases for UserLogin. Case mismatch? [Called from MediaWiki\Special\SpecialPageFactory::getLocalNameFor in /var/www/wiki/includes/specialpage/SpecialPageFactory.php at line 675] in /var/www/wiki/includes/debug/MWDebug.php on line 309
```

**Comment by thaider** [comment]
Thanks for reporting. There was a problem with ```LOGIN-EXT``` that should be fixed now. You've been using it (or ```PERSONAL-EXT```) in your navbar, right? Please test, if the problem persists.

**Comment by Sparc0** [comment]
Page works now when i am logged in.
Else i can only see the navbar.

Also could you update font-awesome to a later version? Else i do it in my local copy :)

**Comment by thaider** [comment]
I updated font awesome to v5.7.1 just two days ago…
