### ISSUE TITLE
Question: How to open the first accordion section

### ISSUE THREAD

**Issue by m-art-in** [thaider/Tweeki#133]
Is it somehow possible to open the first accordion section?

<pre>&lt;div class="panel-group" id="accordion"&gt;
 &lt;accordion parent="accordion" heading="SECTION1"&gt;
   Lorem ipsum...
 &lt;/accordion&gt;
 &lt;accordion parent="accordion" heading="SECTION2"&gt;
   Lorem ipsum...
 &lt;/accordion&gt;
&lt;/div&gt;
</pre>

In the bootstrap documentation they use class=in, but this doesn't work with this code snippet.
Thanks for help

**Comment by thaider** [comment]
should work now...
