### ISSUE TITLE
Embed Video through Tweeki using Bootstrap markup

### ISSUE THREAD

**Issue by GreatWhiteJ** [thaider/Tweeki#135]
Hi,
I'm new to web-dev, this seems straightforward but I can't get this code to run on my site.

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
</div>

Do I need to enable a setting? Maybe add a bootstrap extension? I was under the impression that Tweeki would allow me to embed video using Bootstrap markup.
Help! :)

**Comment by thaider** [comment]
Hi,

this is not a Tweeki or Bootstrap issue. MediaWiki allow only a subset of html tags for security reasons. If you want to embed videos there are specific extensions for that, see [this overview](https://www.mediawiki.org/wiki/Media_Projects)...
