### ISSUE TITLE
Docs...

### ISSUE THREAD

**Issue by viking185** [thaider/Tweeki#137]
Are there any real documentation files or tutorials? I've never used mediawiki or this theme and there is no real information that I can see. Just cryptic half information that gives no insight or example snippets that don't work. Only way i'm able to even change anything currently is file searches for a variable name.

example, trying to add items in a category to the `Tweeki-navbar-left`, no info on where it was located but finally found it in the en.json file. used the sample given `*{{#ask:[[Category:Test]]}}` and all it displays is `[[Category:Test]]` in the submenu. `Test` is a placeholder category name on the site for testing until i get the real data. 

no explination on what #ask even is ... assuming some kind of DB lookup? but why doesn't the category format work? In theory it should look up all posts in the Test category and list them with the appropriate wrapper markup (li in this case) correct? Is there another configuration that's not set correctly that i'm just missing? Someone elses server who is demanding using mediawiki for this project, so no access to the DB just the mediawiki install folder to edit files.

**Comment by thaider** [comment]
Just some hints on what you should make yourself familiar with:
* [MediaWiki's documentation](https://www.mediawiki.org/wiki/MediaWiki) is a great place to start; it's not the best-documented piece of software, but it's not that bad either
* have a look especially at the explanation of MediaWiki's [system messages](https://www.mediawiki.org/wiki/Help:System_message) – there is no need to search Tweeki's files or alter one of them
* [Semantic MediaWiki](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki) is one of MediaWiki's greatest extensions and provides the ```{{#ask:}}``` parser function; you'll have to install it if you want to use this functionality

I'll happily accept any suggestions to improve Tweeki's documentation from a noob's perspective.
