### ISSUE TITLE
Hiding elements for all except

### ISSUE THREAD

**Issue by calebfergie** [thaider/Tweeki#141]
Hi there,

I'm trying to use the `$wgTweekiSkinHideExcept` function but am still seeing the things I want to hide.

I am trying to hide from all but the standard 'Administrators' group created in MediaWiki setup - I've tried both:

`#$wgTweekiSkinHideExcept[array( 'SEARCH' => true, 'sidebar-right' => true, 'TOOLBOX' => true, 'TOOLBOX-EXT' => true)] = ['Administrators'];`

...and simply...

`$wgTweekiSkinHideExcept['sidebar-right'] = ['Administrators'];`

... but elements appear regardless.

Meanwhile, other commands like:

`$wgTweekiSkinHideAll = array( 'SEARCH' => true, 'sidebar-right' => true);`

...work just fine!

Could you please advise?

I'm new to wikis so please let me know if you can provide some more advice on how to use this function. I'm happy to provide more info if its not an obvious issue.

**Comment by thaider** [comment]
Please note that “Administrators” is just the localized display name. ```$wgTweekiSkinHideExcept``` expects the internal name which is ```sysop``` – and which was also used in the example in the documentation, btw ;)

Also: I don't think that 

```#$wgTweekiSkinHideExcept[array( 'SEARCH' => true, 'sidebar-right' => true, 'TOOLBOX' => true, 'TOOLBOX-EXT' => true)] = ['Administrators'];``` 

is valid code and the only reason it doesn't throw an error is probably that the line is commented out (that's what ```#``` does in PHP)... Sorry, if the documentation is not clear enough. How did you come up with this line?

Please confirm that everything works as expected with

```$wgTweekiSkinHideExcept['sidebar-right'] = ['sysop'];```

**Comment by calebfergie** [comment]
Thanks for getting back to me! Much appreciated.

I actually tried `sysop` first, which didn't work for me and prompted me to try `Administrators`. Unfortunately `$wgTweekiSkinHideExcept['sidebar-right'] = ['sysop'];` is not working (the right sidebar still appears for everyone).

Do you know how I can check for the right name of the group? 

I would share a link to the wiki with you, but have not yet configured it's security to a level I am comfortable with - so let me know if there are any key pieces of information I can give you.  

As for the array version, I was just trying to combine your other examples with the `$wgTweekiSkinHideExcept` option and hoping for the best 😄 - I accidentally posted the commented version here, but it actually was not producing an errors that I noticed.

Thanks again for the feedback.

**Comment by thaider** [comment]
Could you please make sure that you're working with newest version of Tweeki. The feature was only introduced 9 days ago. Maybe you have checked out your version before?

**Comment by calebfergie** [comment]
Oh wow, I didn't realize the feature was so new! I will check the diffs of my forked version and the current one.

By the way, [the docs](https://tweeki.thai-land.at/wiki/Welcome) website appears to be down right now.

**Comment by thaider** [comment]
docs should be up again...
