### ISSUE TITLE
Sidebar Content - New Window or Modal.

### ISSUE THREAD

**Issue by calebfergie** [thaider/Tweeki#143]
Hi there,

Thanks again for this skin. I was wondering what the easiest way is to add a button to a sidebar that reveals a **modal**, or at least opens a link in a new window. 

Currently I have [a modal accessible through a template](https://ncp-wiki.herokuapp.com/index.php?title=Template:How-to-play-modal).

On standard pages, I can add this with {{how-to-play}} - but on the sidebar, this creates an error. I see one can create a special navigation element, but I'm not very familiar with PHP.

So I was wondering if you had any recommendations on:
A. How to make a button that opens a link in a new window
B. How to make a navigation element with the contents of this modal.

Thanks for any advice!

**Comment by thaider** [comment]
Hi. The way to go is to use ```$wgTweekiSkinSpecialElements```. Have a look at the [How-To on Showing a text block in a navigational section](https://tweeki.thai-land.at/wiki/How-Tos#Show_a_text_block_in_a_navigational_section). Similarly for a modal something like these lines in ```LocalSettings.php``` should make it work:

```
$wgTweekiSkinSpecialElements['MODAL'] = 'modal';

function modal( $skin, $context ) {
    echo '<button data-toggle="modal" data-target="#myModal">Launch Modal</button>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">…</div>
            </div>
        </div>';
}
```

You should then be able to use ```MODAL``` in navigational sections. You'll probably have to adapt the launch button's classes and stylings…
