### ISSUE TITLE
Can not remove the sidebar

### ISSUE THREAD

**Issue by geraldtruc** [thaider/Tweeki#144]
Hi,

Thanks for this theme, modern. 

I wish to remove the sidebar. I followed [the instructions](https://tweeki.thai-land.at/wiki/How-Tos#Layout) but nothing changes. 

Do you know where the problem comes from?

**Comment by thaider** [comment]
Could you be more specific on what you tried? Have you had a look on the [```$wgTweekiSkinHide…```](https://tweeki.thai-land.at/wiki/Configuration_Options#Hiding_Page_Elements) group of configuration options?

If you're trying to hide it with the [```{{#tweekihide:}}```](https://tweeki.thai-land.at/wiki/Parser_Functions#Tweekihide_parser_function) parser function, make sure, the sidebar you want to hide is listed in ```$wgTweekiSkinHideable``` (```sidebar-right``` is, by default).

**Comment by geraldtruc** [comment]
It works, thank you ;)
