### ISSUE TITLE
Modify navigational elements

### ISSUE THREAD

**Issue by geraldtruc** [thaider/Tweeki#145]
I would like to modify the [navigation elements](https://tweeki.thai-land.at/wiki/Navigation), to reorder them. 

For example, I would like to put the link "discussion", in the sub-menu of "edit-ext". 

I searched everywhere to do, but I did not find. 

Is there documentation or other? 

thanks in advance

**Comment by thaider** [comment]
Have a look at the section about [defining your own special navigational elements](https://tweeki.thai-land.at/wiki/Configuration_Options#Navigational_Elements). It should be possible to overwrite the standard behaviour using ```$wgTweekiSkinNavigationalElements```. Use these lines as a starting point:

```
$wgTweekiSkinNavigationalElements['EDIT-EXT'] = 'myEditExt';

function myEditExt( $skin ) {
  // your replacement code goes here
  // to start copy the code from 
  // https://github.com/thaider/Tweeki/blob/master/includes/TweekiTemplate.php#L214
  // replace all occurences of $this with $skin
}
