### ISSUE TITLE
No sidebars only at main page

### ISSUE THREAD

**Issue by twisterbr** [thaider/Tweeki#147]
Is it possible to set the config below only at main page?
$wgTweekiSkinGridNone = array( 
 "mainoffset" => 0, 
 "mainwidth" => 12 
);

**Comment by thaider** [comment]
I'm not sure, if I get your question right:
- Do you only want to hide the sidebars on the main page? Then, what you're asking for is probably the [```{{#tweekihide:}}```](https://tweeki.thai-land.at/wiki/Parser_Functions#Tweekihide_parser_function) parser function.
- Or do you want to have a special grid for the main page as opposed to other pages where you're also hiding the sidebars? That is currently not possible. Patches are welcome.

**Comment by twisterbr** [comment]
Oh sorry. The second is what I want: to apply the grid config (wgTweekiSkinGridNone) only at main page.
Do you have a path I should follow to accomplish that? newbie here 

>     * Or do you want to have a special grid for the main page as opposed to other pages where you're also hiding the sidebars? That is currently not possible. Patches are welcome.

**Comment by valessiobrito** [comment]
Hi all, how remove sidebar on Special pages?

in code have a comment // TODO: check for situational emptiness of sidebar (e.g. on special pages)

do not support yet?

**Comment by thaider** [comment]
Hi @valessiobrito, see [this new How-To](https://tweeki.thai-land.at/wiki/How-Tos#Hide_navigational_sections_on_specific_namespaces)...

**Comment by thaider** [comment]
@twisterbr you could basically use the same approach as mentioned in the comment above. It would be something like this:

```
$wgHooks['BeforeInitialize'][] = 'onBeforeInitialize';
function onBeforeInitialize( $title ) {
    if( $title->isMainPage() ) {
        $GLOBALS['wgTweekiSkinGridNone'] = [
            'mainoffset' => 4,
            'mainwidth' => 4
        ];
    }
}
```

Make sure to hide the sidebar on the main page with ```{{#tweekihide:sidebar-right}}``` or it won't have any effect...
