### ISSUE TITLE
Official website displays many errors ("already defined", "headers already sent")

### ISSUE THREAD

**Issue by Arthaey** [thaider/Tweeki#148]
I went to https://tweeki.thai-land.at/wiki/Navigation and saw a _bunch_ of errors at the top of the rendered page, before the actual page content.

Here's a screenshot of just some of the errors:

![Screen Shot 2019-06-10 at 7 15 41 AM](https://user-images.githubusercontent.com/71912/59201772-017b1980-8b50-11e9-9f99-a5ea1cf38e3f.png)

**Comment by thaider** [comment]
Thanks for reporting, should be fixed now...
