### ISSUE TITLE
Enabling Tweeki causes MobileFrontend not to work

### ISSUE THREAD

**Issue by Reception123** [thaider/Tweeki#150]
When Tweeki is enabled, MobileFrontend doesn't work and pages do not display (there is no content).

Have the latest Tweeki version and MediaWiki 1.33

**Comment by thaider** [comment]
Thanks for reporting and sorry for the late response. If you still have to possibility to check it, could you please confirm if the problem persists with the latest version of Tweeki?

**Comment by Reception123** [comment]
Sorry, it does indeed seem to work now. Thanks!

**Comment by thaider** [comment]
Thanks, that's great to hear!
