### ISSUE TITLE
edit keyboard shortcut not working with EDIT-EXT

### ISSUE THREAD

**Issue by yombo** [thaider/Tweeki#159]
Tweeki Version: 1.1.1, commit: 2b3a3e1f1681b5d9b0278e4010fb783849b85f93
Mediawiki Version 1.34.1

MediaWiki:Tweeki-navbar-right:
EDIT-EXT,TOOLBOX-EXT,PERSONAL,LOGIN,SEARCH

https://yombo.net/MediaWiki:Tweeki-sidebar-right
TOC

Where to see the error:
Webstie: https://dccwiki.com

---

Other shortcuts work, such as CTL-ALT-M (move), CTL-ALT-D (delete).

However, CTL-ALT-E doesn't work.

--
If I use this:
MediaWiki:Tweeki-navbar-right:
EDIT,TOOLBOX-EXT,PERSONAL,LOGIN,SEARCH

CTL-ALT-E works just fine, along with all other shortcuts.

**Comment by thaider** [comment]
Thanks for reporting, should be fixed now...
