### ISSUE TITLE
I want delete edit for anon users

### ISSUE THREAD

**Issue by SamueloWeb** [thaider/Tweeki#160]
hello i want to remove the edit button for anonymous users and show only the text

**Comment by thaider** [comment]
Hi. If you're using the default setup with ```EDIT-EXT``` in the right sidebar, you can hide it for anonymous users by putting the following line in ```LocalSettings.php```:

```
$wgTweekiSkinHideAnon['EDIT-EXT'] = true;
```

You could hide the sidebar altogether with this line:

```
$wgTweekiSkinHideAnon['sidebar-right'] = true;
```
