### ISSUE TITLE
Tweeki fails under mediawiki 1.35

### ISSUE THREAD

**Issue by tuxmaster5000** [thaider/Tweeki#163]
The skin fails with an call to an undefined method.
See the picture:
![7dd8f6fee5a842c1a951e155a7cf48f8](https://user-images.githubusercontent.com/837503/94810289-1f7b2600-03f4-11eb-8c92-090ce4a9e1b6.png)

The functions was deprecated since 1.28.
https://www.mediawiki.org/wiki/Topic:Vj94nk4mug1yfn1t

**Comment by tuxmaster5000** [comment]
It looks like the fix will be:
$parser->getOutput()->updateCacheExpiry()
instant of
$parser->disableCache();
https://doc.wikimedia.org/mediawiki-core/REL1_34/php/classCacheTime.html#a70f26801bc209cfb19bd3fa888102dee

**Comment by Fredrilj** [comment]
Tweeki seems to work without any cache expiry errors on MW 1.34.2.

I'm only a few weeks into a project to convert a 70k page wiki to use Tweeki, but get a little skeptical when errors like this are not detected earlier, and Tweeki is not updated in step with Bootstrap.

**Comment by thaider** [comment]
Thanks for reporting and suggesting a fix! I chose a different approach: the cache is not disabled completely but rather a user's group memberships are now put into the [Page Rendering Hash](https://www.mediawiki.org/wiki/Manual:Hooks/PageRenderingHash).

It's unfortunate that MediaWiki's documentation still features the removed function e.g. [here](https://www.mediawiki.org/wiki/Manual:Tag_extensions#How_do_I_disable_caching_for_pages_using_my_extension?) or [here](https://www.mediawiki.org/wiki/Manual:Parser_functions#Caching).

**Comment by thaider** [comment]
As #165 reported, my approach actually didn't work. Change to use of ``` $parser->getOutput()->updateCacheExpiry(0)``` as proposed by OP.
