### ISSUE TITLE
Is Tweeki a Dead Project?

### ISSUE THREAD

**Issue by Fredrilj** [thaider/Tweeki#164]
Seems that Tweeki is hardly being updated for the past 2 years and do not bother to keep up with new Bootstrap versions.

Is skin [Chameleon](https://www.mediawiki.org/wiki/Skin:Chameleon) a better choice for a serious wiki project?

**Comment by thaider** [comment]
Hi. Tweeki's still being maintained and a release supporting Bootstrap 4 is in preparation and will be published soon. You can check it out in this repository's development branch. In order to enable Bootstrap 4 you would have to add the line 

```$wgTweekiSkinUseBootstrap4 = true;```

 to your ```LocalSettings.php```.

**Comment by GodMorduk** [comment]
@thaider is there a way to load custom themes is BS4 version? It looks amazing, but custom themes (from bootswatch for example) would be useful too

**Comment by thaider** [comment]
@GodMorduk [the old way of doing it](https://tweeki.kollabor.at/wiki/How-Tos#Completely_replace_bootstrap_files_with_customized_versions) should still work but I haven't tested it recently. If you're familiar with webpack, note that Tweeki supports it, too. It's not documented yet but it allows you to use Bootswatch's ```.scss``` files.
