### ISSUE TITLE
Wikitables class not displaying on tables after upgrading

### ISSUE THREAD

**Issue by thecornerinvasion** [thaider/Tweeki#166]
Hello,

I had to upgrade MediaWiki and Tweeki to the latest stable versions. After I did so, the only visible change that happened to my wiki pages is that any formatting from wikitable class tables was now gone. I've yet to find a solution to this issue. Some help would be appreciated. 

Thank you.

**Comment by thaider** [comment]
Thanks for reporting, should be fixed...
