### ISSUE TITLE
[1.1.2] fails under MW 1.35 with class not found.

### ISSUE THREAD

**Issue by tuxmaster5000** [thaider/Tweeki#167]
On the last LTS version of MW, tweeki fails with:
` Error from line 878 of mediawiki/skins/Tweeki/includes/Hooks.php: Class 'HTMLArmor' not found`

**Comment by tuxmaster5000** [comment]
As far as I can see, this is an typo.
See https://www.mediawiki.org/wiki/Manual:HtmlArmor.php
It looks like, it must be HtmlArmor instant of HTMLArmor.

**Comment by tuxmaster5000** [comment]
It comes from  https://github.com/thaider/Tweeki/issues/154#issue-566462053

**Comment by thaider** [comment]
Hi. Thanks for reporting. Did you apply the OP's proposed patch from #154 yourself or did you maybe use a fork of Tweeki? I can't find the typo in the current code...

**Comment by tuxmaster5000** [comment]
@thaider It was only in the first comment of the thread. But then in the repo, the correct version was used,

**Comment by thaider** [comment]
@tuxmaster5000 I'm not sure if I interpret your answer correctly. Could you please confirm, if the problem occurs with the current version in the repo?

**Comment by tuxmaster5000** [comment]
No, the git repo is clean, only in the github thread exits the typo.

**Comment by thaider** [comment]
ok, thanks!
