### ISSUE TITLE
Cannot Hide EDIT Navigational Element

### ISSUE THREAD

**Issue by Jyosua** [thaider/Tweeki#169]
I looked at the documentation and was trying to hide the Edit button from non-logged in users. I did the following:
```$wgTweekiSkinHideAnon = [ 'EDIT' => true ];```
But this didn't seem to work. I had tried to add EDIT and ca-edit to `$wgTweekiSkinHideable` as described [here](https://tweeki.kollabor.at/wiki/How-Tos) and [here](https://tweeki.kollabor.at/wiki/Navigation) but this doesn't seem to work either...

This was with MediaWiki 1.35.0 and Tweeki 1.1.2.

**Comment by Jyosua** [comment]
Looks like this was actually because, although the EDIT button is what is shown to non-logged-in users, the sidebar-right was configured to use EDIT-EXT by default, so if you want to hide it, that's what you have to list in SkinHideAnon

**Comment by thaider** [comment]
Thanks for reporting and investigation. Do you think it should be clarified somewhere in the documentation?

**Comment by Jyosua** [comment]
Yeah, I think it would be helpful. In the navigation documentation, it mentions that EDIT-EXT appearance is reduced to EDIT for instances where the extra features are hidden by default, but I think it would be helpful to mention somewhere in this area that you need to use the element name that is specified in the template, not the one that happens to be displayed.

**Comment by thaider** [comment]
Done, thanks!
