### ISSUE TITLE
 setupSkinUserCss is deprecated: skin renders unstyled

### ISSUE THREAD

**Issue by jdlrobson** [thaider/Tweeki#170]
Impact: the stylesheet for the skins do not load

To address this you can follow the example here:
https://gerrit.wikimedia.org/r/c/mediawiki/skins/Nimbus/+/639875
Let me know if you need any help!

**Comment by thaider** [comment]
Thanks for reporting!

As loading the styles is conditional in Tweeki's case, Nimbus' solution wasn't applicable – I decided to go with the ```BeforePageDisplay``` hook...
