### ISSUE TITLE
Force the div (main content) to extend to the footer

### ISSUE THREAD

**Issue by Olivia1373** [thaider/Tweeki#177]
Hello,

So that set a background I would like the main content section to display by default from the navbar until footer at the bottom, as on this wiki [https://matana.education.gov.il/K](https://matana.education.gov.il/K)
How should I go about getting this result ?

**Comment by thaider** [comment]
Hi,

I'm not completely sure but I suppose, they used a [custom PageRenderer](https://tweeki.kollabor.at/wiki/Configuration_Options#Page_Layout). With it you can implement any layout you like using Tweeki's building blocks...
