### ISSUE TITLE
Loading Tweeki affects other skins

### ISSUE THREAD

**Issue by dhowland** [thaider/Tweeki#178]
adding `wfLoadSkin( 'Tweeki' );` to `LocalSettings.php` messes up the styling of the default Vector skin.

**Comment by thaider** [comment]
Hi. Thanks for reporting! Could you please try, if the latest commit fixes the problem? Thanks!

**Comment by dhowland** [comment]
Yes I think that's better.  This is a fresh wiki install I'm working with so there is only the default main page, but the obviously broken styling is gone.

**Comment by thaider** [comment]
great, thanks!
