### ISSUE TITLE
( ! ) Deprecated: Use of Parser::Options was deprecated in MediaWiki 1.35.

### ISSUE THREAD

**Issue by jdlrobson** [thaider/Tweeki#181]
[Called from TweekiTemplate::renderCustomNavigation in /vagrant/mediawiki/skins/Tweeki/includes/TweekiTemplate.php at line 1123] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 329

Seen on https://skins.wmflabs.org/?#/skin/tweeki

**Comment by thaider** [comment]
thanks for reporting! should be fixed now...
