### ISSUE TITLE
Deprecated: Use of BaseTemplate::getToolbox was deprecated in MediaWiki 1.35

### ISSUE THREAD

**Issue by jdlrobson** [thaider/Tweeki#182]
( ! ) Deprecated: Use of BaseTemplate::getToolbox was deprecated in MediaWiki 1.35. [Called from TweekiTemplate::renderNavigation in /vagrant/mediawiki/skins/Tweeki/includes/TweekiTemplate.php at line 405] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 329

This can be fixed by replacing the call with `$this->get('sidebar')['TOOLBOX']`. Let me know if you need any help!

**Comment by thaider** [comment]
thanks for reporting!
