### ISSUE TITLE
"tweeki-navbar-left": "" render error 

### ISSUE THREAD

**Issue by Breaeth** [thaider/Tweeki#184]
Hello, first i would like to say thanks to all of this work, this skin is actually amazing thank you so much ! 

So,  on MW 1.35.1 when i want to add something in the tweeki-navbar-left in the `file` en.json
ex : 
tweeki-navbar-left": "Exemple",

All of my wiki page wich are already start can't load there is no render anymore 
But it's still render my index page, some special page and the page of page creation 

Using bs3 or bs4 change anything of the problem.

Good day to you, with admiration,
Breaeth.

PS : if you are interest i have add iconify for the management of the icon it's much more complete and easy than awesome font.But i didn't find a way to insert a external script in the tweeki spirit so my solution isn't very graceful. 
PS2 : I have also correct few very little dysplay imperfection ,  i will make other bugs issues for present those very little dysplay imperfection and how i have correct them, if you are interest obviously.

**Comment by thaider** [comment]
Hi. Thanks for the report. You probably have a syntax error in the file. JSON doesn't allow arrays to end with a common (as does PHP), so if your en.json ends with
```
"tweeki-navbar-left": "Exemple",
```
you should replace it with
```
"tweeki-navbar-left": "Exemple"
```
(without the comma at the end).

If your wiki blanks out you should turn error reporting on, to find out what's the reason for that. See [MediaWiki's documentation](https://www.mediawiki.org/wiki/Manual:How_to_debug#PHP_errors) for the details.

Anyway **you shouldn't edit the message files directly**. Instead [override the messages on-wiki](https://www.mediawiki.org/wiki/Help:System_message#Overriding_messages_on-wiki), so you can safely update the skin without losing your modifications.

Suggestions for improvements of styles are always warmly welcome! Thanks for sharing.

**Comment by Breaeth** [comment]
Thanks for your answer i know now out to fix this. Thanks
