### ISSUE TITLE
[1.2.1] Mediawiki 1.35.1 unable to login

### ISSUE THREAD

**Issue by tuxmaster5000** [thaider/Tweeki#185]
When using the tweeki skin as the default skin, nobody can log into the wiki.
The use will only see an blank page. When enable the debug mode of MW, then this error will shown in the browser console:

> [X-w9iE4kG7f@OR7tHvgQjAAAAI4] /load.php?lang=en&modules=startup&only=scripts&raw=1&skin=tweeki   BadMethodCallException from line 851 of /usr/share/mediawiki/includes/session/SessionManager.php: Sessions are disabled for this entry point
> Backtrace:
> #0 /usr/share/mediawiki/includes/session/SessionManager.php(220): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
> #1 /usr/share/mediawiki/includes/WebRequest.php(826): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
> #2 /usr/share/mediawiki/includes/user/User.php(1221): WebRequest->getSession()
> #3 /usr/share/mediawiki/includes/user/User.php(388): User->loadFromSession()
> #4 /usr/share/mediawiki/includes/user/User.php(2125): User->load()
> #5 /usr/share/mediawiki/includes/user/User.php(3064): User->getId()
> #6 /usr/share/mediawiki/includes/user/UserOptionsManager.php(584): User->isRegistered()
> #7 /usr/share/mediawiki/includes/user/UserOptionsManager.php(487): MediaWiki\User\UserOptionsManager->getCacheKey(User)
> #8 /usr/share/mediawiki/includes/user/UserOptionsManager.php(135): MediaWiki\User\UserOptionsManager->loadUserOptions(User, integer)
> #9 /usr/share/mediawiki/includes/user/User.php(2665): MediaWiki\User\UserOptionsManager->getOption(User, string, NULL, boolean)
> #10 /usr/share/mediawiki/includes/context/RequestContext.php(416): User->getOption(string)
> #11 /usr/share/mediawiki/includes/context/ContextSource.php(150): RequestContext->getSkin()
> #12 /usr/share/mediawiki/skins/Tweeki/includes/Hooks.php(52): ContextSource->getSkin()
> #13 /usr/share/mediawiki/includes/HookContainer/HookContainer.php(320): TweekiHooks::onParserFirstCallInit(Parser)
> #14 /usr/share/mediawiki/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
> #15 /usr/share/mediawiki/includes/HookContainer/HookRunner.php(2959): MediaWiki\HookContainer\HookContainer->run(string, array)
> #16 /usr/share/mediawiki/includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
> #17 /usr/share/mediawiki/includes/parser/Parser.php(477): Parser->firstCallInit()
> #18 /usr/share/mediawiki/includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
> #19 /usr/share/mediawiki/includes/ServiceWiring.php(818): ParserFactory->create()
> #20 /usr/share/mediawiki/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
> #21 /usr/share/mediawiki/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
> #22 /usr/share/mediawiki/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
> #23 /usr/share/mediawiki/includes/cache/MessageCache.php(1249): MediaWiki\MediaWikiServices->getParser()
> #24 /usr/share/mediawiki/includes/cache/MessageCache.php(1228): MessageCache->getParser()
> #25 /usr/share/mediawiki/includes/language/Message.php(1287): MessageCache->transform(string, boolean, LanguageEn, NULL)
> #26 /usr/share/mediawiki/includes/language/Message.php(894): Message->transformText(string)
> #27 /usr/share/mediawiki/includes/language/Message.php(954): Message->toString(string)
> #28 /usr/share/mediawiki/includes/EditPage.php(3840): Message->text()
> #29 /usr/share/mediawiki/extensions/VisualEditor/includes/VisualEditorDataModule.php(70): EditPage::getCopyrightWarning(Title, string, string)
> #30 /usr/share/mediawiki/extensions/VisualEditor/includes/VisualEditorDataModule.php(25): VisualEditorDataModule->getMessageInfo(ResourceLoaderContext)
> #31 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(736): VisualEditorDataModule->getScript(ResourceLoaderContext)
> #32 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
> #33 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
> #34 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderStartUpModule.php(209): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
> #35 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderStartUpModule.php(405): ResourceLoaderStartUpModule->getModuleRegistrations(ResourceLoaderContext)
> #36 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(736): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
> #37 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
> #38 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
> #39 /usr/share/mediawiki/includes/resourceloader/ResourceLoader.php(775): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
> #40 [internal function]: ResourceLoader->{closure}(string)
> #41 /usr/share/mediawiki/includes/resourceloader/ResourceLoader.php(787): array_map(Closure, array)
> #42 /usr/share/mediawiki/includes/resourceloader/ResourceLoader.php(874): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
> #43 /usr/share/mediawiki/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
> #44 /usr/share/mediawiki/load.php(38): wfLoadMain()
> #45 {main} load.php:51:48
> 

Using other skins will work.

**Comment by thaider** [comment]
Thanks for reporting! I can't reproduce the error on a vanilla installation of MW 1.35.1 and Tweeki 1.2.1 (b3de6ea). 

* could you try to only load Tweeki and no other skins or extensions – does that change anything?
* what's the ```$wgGroupPermissions``` settings for your wiki?
* if you [turn PHP errors on](https://www.mediawiki.org/wiki/Manual:How_to_debug#PHP_errors) and set ```$wgShowExceptionDetails``` to true in ```LocalSettings.php``` – what's shown instead of the blank page?

**Comment by tuxmaster5000** [comment]
Disable the extensions are not really possible, because we need the ldap plugins to log into it.
So when I disable the ldap plug-in then I can't log into the wiki. And blank page comes only after the successful log on.
Enter wrong credentials will result in an normal error page about it. 

> $wgGroupPermissions:
> $wgGroupPermissions['*']['autocreateaccount'] = true;
> $wgGroupPermissions['*']['createaccount'] = false;
> $wgGroupPermissions['*']['edit'] = false;
> $wgGroupPermissions['*']['read'] = false;

With the php setings:
$wgShowExceptionDetails = true;
Also only the blank page. The error is only visible on the web console of firefox.

**Comment by tuxmaster5000** [comment]
Do you mean the last git master one? Because I use still the last released one.

**Comment by thaider** [comment]
Yes, I'm talking about master.

**Comment by tuxmaster5000** [comment]
I tryed with the last master:
Now I can log in, but in the firefox console I see this exception:
[YEsIcNRKx2CTo8qgwm9TPgAAAMM] /load.php?lang=en&modules=startup&only=scripts&raw=1&skin=tweeki   BadMethodCallException from line 851 of /usr/share/mediawiki/includes/session/SessionManager.php: Sessions are disabled for this entry point

> Backtrace:
> #0 /usr/share/mediawiki/includes/session/SessionManager.php(220): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
> #1 /usr/share/mediawiki/includes/WebRequest.php(826): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
> #2 /usr/share/mediawiki/includes/user/User.php(1221): WebRequest->getSession()
> #3 /usr/share/mediawiki/includes/user/User.php(388): User->loadFromSession()
> #4 /usr/share/mediawiki/includes/user/User.php(2125): User->load()
> #5 /usr/share/mediawiki/includes/user/User.php(3064): User->getId()
> #6 /usr/share/mediawiki/includes/user/UserOptionsManager.php(584): User->isRegistered()
> #7 /usr/share/mediawiki/includes/user/UserOptionsManager.php(487): MediaWiki\User\UserOptionsManager->getCacheKey(User)
> #8 /usr/share/mediawiki/includes/user/UserOptionsManager.php(135): MediaWiki\User\UserOptionsManager->loadUserOptions(User, integer)
> #9 /usr/share/mediawiki/includes/user/User.php(2665): MediaWiki\User\UserOptionsManager->getOption(User, string, NULL, boolean)
> #10 /usr/share/mediawiki/includes/context/RequestContext.php(416): User->getOption(string)
> #11 /usr/share/mediawiki/includes/context/ContextSource.php(150): RequestContext->getSkin()
> #12 /usr/share/mediawiki/skins/Tweeki/includes/Hooks.php(52): ContextSource->getSkin()
> #13 /usr/share/mediawiki/includes/HookContainer/HookContainer.php(320): TweekiHooks::onParserFirstCallInit(Parser)
> #14 /usr/share/mediawiki/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
> #15 /usr/share/mediawiki/includes/HookContainer/HookRunner.php(2959): MediaWiki\HookContainer\HookContainer->run(string, array)
> #16 /usr/share/mediawiki/includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
> #17 /usr/share/mediawiki/includes/parser/Parser.php(477): Parser->firstCallInit()
> #18 /usr/share/mediawiki/includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
> #19 /usr/share/mediawiki/includes/ServiceWiring.php(818): ParserFactory->create()
> #20 /usr/share/mediawiki/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
> #21 /usr/share/mediawiki/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
> #22 /usr/share/mediawiki/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
> #23 /usr/share/mediawiki/includes/cache/MessageCache.php(1249): MediaWiki\MediaWikiServices->getParser()
> #24 /usr/share/mediawiki/includes/cache/MessageCache.php(1228): MessageCache->getParser()
> #25 /usr/share/mediawiki/includes/language/Message.php(1287): MessageCache->transform(string, boolean, LanguageEn, NULL)
> #26 /usr/share/mediawiki/includes/language/Message.php(894): Message->transformText(string)
> #27 /usr/share/mediawiki/includes/language/Message.php(954): Message->toString(string)
> #28 /usr/share/mediawiki/includes/EditPage.php(3840): Message->text()
> #29 /usr/share/mediawiki/extensions/VisualEditor/includes/VisualEditorDataModule.php(70): EditPage::getCopyrightWarning(Title, string, string)
> #30 /usr/share/mediawiki/extensions/VisualEditor/includes/VisualEditorDataModule.php(25): VisualEditorDataModule->getMessageInfo(ResourceLoaderContext)
> #31 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(736): VisualEditorDataModule->getScript(ResourceLoaderContext)
> #32 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
> #33 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
> #34 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderStartUpModule.php(209): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
> #35 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderStartUpModule.php(405): ResourceLoaderStartUpModule->getModuleRegistrations(ResourceLoaderContext)
> #36 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(736): ResourceLoaderStartUpModule->getScript(ResourceLoaderContext)
> #37 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(704): ResourceLoaderModule->buildContent(ResourceLoaderContext)
> #38 /usr/share/mediawiki/includes/resourceloader/ResourceLoaderModule.php(839): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
> #39 /usr/share/mediawiki/includes/resourceloader/ResourceLoader.php(775): ResourceLoaderModule->getVersionHash(ResourceLoaderContext)
> #40 [internal function]: ResourceLoader->{closure}(string)
> #41 /usr/share/mediawiki/includes/resourceloader/ResourceLoader.php(787): array_map(Closure, array)
> #42 /usr/share/mediawiki/includes/resourceloader/ResourceLoader.php(874): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
> #43 /usr/share/mediawiki/load.php(51): ResourceLoader->respond(ResourceLoaderContext)
> #44 /usr/share/mediawiki/load.php(38): wfLoadMain()
> #45 {main}

Disable the skin, no souch excepion will shown.

**Comment by thaider** [comment]
If possible, could you confirm if the latest pull request by Palladox (#200) solved the problem?

**Comment by tuxmaster5000** [comment]
Today I tested the last git master, this will work. Can you release it?
Thanks
