### ISSUE TITLE
[1.2.1] Return value of Parser::getTitle()

### ISSUE THREAD

**Issue by LeoCahyadi** [thaider/Tweeki#186]
When refreshing/reloading (F5) a page (with sidebar), this error occured:

> Fatal error: Uncaught TypeError: Return value of Parser::getTitle() must be an instance of Title, null returned in /home/gbidbr/public_html/w1350/includes/parser/Parser.php:1007 
>
> Stack trace:
#0 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/Hooks.php(618): Parser->getTitle()
#1 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/Hooks.php(483): TweekiHooks::parseButtonLink(Array, Object(Parser), false)
#2 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(1144): TweekiHooks::parseButtons('mainpage\n\nPerih...', Object(Parser), false)
#3 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(1106): TweekiTemplate->renderCustomNavigation(Array, Array)
#4 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(911): TweekiTemplate->buildItems('mainpage,\nPerih...', Array, 'navbar-left')
#5 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(871): TweekiTemplate->renderNavbarElement4('left')
#6 /home/gbidbr/public_html/w1350/skins/Tweeki/includes in /home/gbidbr/public_html/w1350/includes/parser/Parser.php on line 1007

But if I add {{#tweekihide:sidebar-right}} in that page, this error is no longer occured.

**Comment by thaider** [comment]
Thanks for reporting! Could you please confirm, if be702f6 fixes this? Also could you please report the content of ```sidebar-right```? Thanks!

**Comment by LeoCahyadi** [comment]
Hi, the error still occured:

> Fatal error: Uncaught TypeError: Return value of Parser::getTitle() must be an instance of Title, null returned in /home/gbidbr/public_html/w1350/includes/parser/Parser.php:1007
>
>Stack trace:
>#0 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/Hooks.php(526): Parser->getTitle() 
>#1 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/Hooks.php(483): TweekiHooks::parseButtonLink('mainpage', Object(Parser), false) 
>#2 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(1175): TweekiHooks::parseButtons('mainpage\n\nPerih...', Object(Parser), false)
>#3 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(1137): TweekiTemplate->renderCustomNavigation(Array, Array) 
>#4 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(942): TweekiTemplate->buildItems('mainpage,\nPerih...', Array, 'navbar-left') 
>#5 /home/gbidbr/public_html/w1350/skins/Tweeki/includes/TweekiTemplate.php(902): TweekiTemplate->renderNavbarElement4('left') 
>#6 /home/gbidbr/public_html/w1350/skins/Tweeki/inc in /home/gbidbr/public_html/w1350/includes/parser/Parser.php on line 1007

Content of MediaWiki:Tweeki-sidebar-right:
> EDIT-EXT,TOC

And I can't seem to logout also, since it causes error when accessing Special:Logout.

**Comment by polydem** [comment]
I also heve still the exact same problem, and the #be702706 didn't seem to fix the problem. Which ever content I put on each sidebar I have the same problem.

**Comment by thaider** [comment]
Sorry for the late response. It took me a while to figure this out. Could you please check, if the latest commit solves the problem, @polydem @aytimothy ? Thanks!

**Comment by polydem** [comment]
@thaider Thank you very much for your work!! The problem is now completely fixed!!

**Comment by LeoCahyadi** [comment]
@thaider Confirmed, it's working now. Thanks!
