### ISSUE TITLE
I want to add history and discussion to the navigation bar separately.

### ISSUE THREAD

**Issue by michiOO** [thaider/Tweeki#187]
I want to add history, discussion or other elements to Tweeki-navbar-left, mainly
I'd like to add history, discussions or other elements individually. I'd like to add history, discussions or other elements to the Tweeki-navbar-left, like edit, which is currently available separately.
If possible, I'd like to add an icon like edit.

I'm not a developer, and I'm not sure if it's possible to use $wgTweakingSkinNavigationalElements.
I'm not a developer and I don't speak English, so it's difficult.
I would like to know the reference code.

**Comment by thaider** [comment]
Thanks for reporting! I added ```HISTORY```to the list of navigational elements, note that ```TALK```already existed.

It's possible to define the icons that should be used by editing the following messages:
```
tweeki-namespace-talk-icon
tweeki-history-icon
```

```$wgTweekiSkinNavigationalElements``` can indeed be used to define new elements or overwrite existing ones. It's not difficult to do it requires some basic understanding of PHP, however.

**Comment by michiOO** [comment]
I was able to add it.
I haven't tried ICON yet, but I will.

Thank you very much. Thank you very much.

**Comment by michiOO** [comment]
tweeki-namespace-talk-icon
tweeki-history-icon

I've set the icons above, but they are not reflected in tweeki-navbar-left. Also, the edit icon doesn't show up anymore.

I thought it was a problem with the Mediawiki version, so I updated to Mediawiki 1.35.1, but it didn't show up. Is this just a problem with me?

Please check.
