### ISSUE TITLE
Mysterious parsing in navbar messages

### ISSUE THREAD

**Issue by sneakers-the-rat** [thaider/Tweeki#191]
What do you suppose is going on here...

<img width="846" alt="Screen Shot 2021-03-25 at 9 30 58 PM" src="https://user-images.githubusercontent.com/12961499/112577467-9b599800-8db1-11eb-83f9-c3e004c0bb00.png">

Where `Minutes`, the name of a page, is parsed as $1 minutes whenever it is by itself. If i modify it at all like `\Minutes` or etc. then it prints as expected, but then no longer links to the `[[Minutes]]` page. Doesn't matter what position it is in the list. Doesn't happen when linked normally. I would suspect some misapplied semantic parser or something but... it's dollars.. for minutes...

don't know what other information you need from me on this, lmk, but i'm pretty baffled.

**Comment by thaider** [comment]
The reason is that there's a message with the name „Minutes“. Tweeki's [button syntax parser](https://tweeki.kollabor.at/wiki/Buttons#Parsing) looks, if messages exist and if so, replaces the original string. See the [documentation](https://tweeki.kollabor.at/wiki/Buttons#Parsing) for workarounds...

**Comment by sneakers-the-rat** [comment]
aha! thank you :) I was hunting around the docs looking for a description of the syntax for messages, didn't think to look on the buttons page! This seems like an edge case, but might be worth giving a link at the top of the messages docs saying 'for more details about the syntax to specify buttons within messages, see here' to avoid having to deal with pesky issues like these ;) Love the skin btw!
