### ISSUE TITLE
[1.2.1] Mediawiki 1.35.2 Accordion broken

### ISSUE THREAD

**Issue by m-art-in** [thaider/Tweeki#192]
Since my update from Mediawiki 1.35.1 to 1.35.2, the <accordion> tag no longer works. It simply displays the code on the page.

![grafik](https://user-images.githubusercontent.com/15324884/114519058-4d151780-9c40-11eb-807f-b2cbc52e4a2c.png)

With the Vector skin I now even get an error:
![grafik](https://user-images.githubusercontent.com/15324884/114518934-2a82fe80-9c40-11eb-969a-159fb880bfc0.png)
 
What do I have to do? Have stricter security policies been introduced with the update? Other than that, I haven't changed anything on my installation.

**Comment by m-art-in** [comment]
Postscript:
i am using bootstrap 3 and now i have added the sample code on a new wiki page and now i get this view:
![grafik](https://user-images.githubusercontent.com/15324884/114522608-d0843800-9c43-11eb-970c-f077cf51561e.png)

That means the code is ignored and displayed as escaped text...

**Comment by thaider** [comment]
Could you try, if the latest pull request by Palladox (#200) solves the issue? Also, please be aware that support for BS3 will be dropped in the near future...

**Comment by m-art-in** [comment]
Sorry for the late repley. The new version fixed the problem.
