### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by DavidRose333** [thaider/Tweeki#195]
Hello   :-)

Firstly, is the the right place to be asking for general help with configuration of a wiki newly skinned with Tweeki?

I have basic knowledge of HTML and CSS and no programming skills.

I have acquired my first  wiki ---> https://moma.miraheze.org/wiki/Main_Page

Because I am a visual thinker I wanted to change the skin first **so I can see how the website is looking as I build it**, but I am wondering now (given my skill level) if it might be better to build some structure and content first and then later change the skin to Tweeki (revert to the default skin and start building a website).

**I really like the look and structure of   https://tweeki.kollabor.at/wiki   and want to build a site pretty much like it.**

If am to keep Tweeki skin for now (not reverting to default skin) should I implement all the steps listed at  https://tweeki.kollabor.at/wiki/Configuration_Options   ?

If so my, next quesstion would be:

Is there any reason why I would not opt for Bootstrap 4 at  miraheze.org farm?

I would really appreciate any advice.

Thanks for your time and consideration.

Rosie

**Comment by DavidRose333** [comment]
Would it be possible to install a clone of  https://tweeki.kollabor.at/wiki  at  https://moma.miraheze.org/wiki/  ???

Then I could just swap over to my images, text, etc.

I have **chemo brain** which effects my concentration and my capacity to process complex new ideas. I would really like to try and learn this wiki management and content creation but feeling a bit overwhelmed with the configuration of my wiki for Tweeki  and  working with PHP.

perhaps a volunteer Mentor might help,

Thanks

Rosie

**Comment by DavidRose333** [comment]
I have checked with miraheze.org

#miraheze IRC Channel 14th May:

<MirahezeBot> rosie: 2021-05-14 - 05:21:01UTC <dmehus> tell rosie Regarding your message, yes, it would be possible import an XML dump from https://tweeki.kollabor.at/wiki, provided the wiki is either (a) licensed under a free license or (b) licensed to you with provisions that allow for you to reuse and make adaptations to it. We'd need some evidence from the wiki's owners/contributors that they're providing you with said license
<rosie> @dmehus thanks for that advice. I will see if I can find out about (a) and then if not available follow up on option (b) ... I have left a message at https://github.com/thaider/Tweeki/issues/195  (I hope that is the right place) It seems to my newbie eyes that Thaider is looking after Tweeki
<MirahezeBot> [ Newbie Question · Issue #195 · thaider/Tweeki · GitHub ] - github.com
...
<rosie> there is no licence information relevant to the wiki  https://tweeki.kollabor.at/wiki/  shown on the website, so I will try to get permission form the creator of the wiki

**Comment by thaider** [comment]
Hi Rosie,

if you want to imitate the look of a specific page of the documentation you can just append ```?action=edit``` to the URL to see the page's source code, e.g. for the welcome page it would be https://tweeki.kollabor.at/wiki/Welcome?action=edit

I would recommend opting in for Bootstrap 4, it will be the default in a soon to be released version and support for Bootstrap 3 will be dropped at some point.

The other configuration options are all optional, most of the configuration is done with system messages. If you want your page to look similar to the documentation have a look at [the documentation of the setup](https://tweeki.kollabor.at/wiki/Setup_for_tweeki.kollabor.at).

**Comment by DavidRose333** [comment]
Thank you Tobias for your help. 

I am feeling more confident now I have played a little with the wiki ... realize I just need to take one step at a time and take it slowly (and not work when I am tired LOL).... I will attempt to follow those instructions of yours.

:-)
