### ISSUE TITLE
Tweeki.css does not respond when the setting is Special:Global preferences

### ISSUE THREAD

**Issue by michiOO** [thaider/Tweeki#199]
Tweeki.css does not respond when the setting is Special:Global preferences page.
Please let me know how to fix this.
I'm using bootstrap4.

**Comment by thaider** [comment]
see the documentation for the [```$wgAllowSiteCSSOnRestrictedPages```](https://www.mediawiki.org/wiki/Manual:$wgAllowSiteCSSOnRestrictedPages) configuration setting for an explanation why that is the case and how you can change the behaviour...
