### ISSUE TITLE
Should admin/thaider enable discussions?

### ISSUE THREAD

**Issue by Fredrilj** [thaider/Tweeki#202]
Github has a feature called discussions. When enabled we can have open conversations in a public forum.
https://docs.github.com/en/discussions/quickstart

It seems to be difficult to get help with Tweeki tweaking, but I'm sure we are users that would like to help each other

Should discussions be enabled or is it better to use the Tweeki talkpage on mediawiki.org?

**Comment by thaider** [comment]
I'm definitely open to enabling the feature, if there's enough interest. To whoever is following the discussion: could you please react with an emoji or something if you support the proposal! Any experiences with it?

**Comment by kghbln** [comment]
Isn't the [talk page on the wiki](https://www.mediawiki.org/wiki/Skin_talk:Tweeki) meant for just this type of things. I personally think this makes more sense for repo that do not have something like this at hand. Is appears to be hard enough to get the issue reports to GitHub.
