### ISSUE TITLE
Navbar doesn't respond to changes in MediaWiki namespace alterations.

### ISSUE THREAD

**Issue by gustavormello** [thaider/Tweeki#203]
Hi guys,

I installed Tweeki in my system and everything seems to be working OK, but I can't costumize the navbar.

Screenshot: https://ibb.co/cvWCYV3

Where you can see the problem:
http://thegrove.com.br/metodo/index.php?title=MediaWiki:Tweeki-navbar-left

I tried disabling other extensions but wasn't very lucky. Not sure I missed one or what might be the problem.

Mediawiki version: 1.35.2
Tweeki version: 1.2.1

**Comment by thaider** [comment]
This is strange. Might be an internationalization issue. What's your wiki's Language and what's the language set in your preferences? Did you change the wiki's language at some point?

**Comment by gustavormello** [comment]
The language was "pt-BR" in both LocalSettings.php and in my preferences. I tried changing it to English but still have the same issue.

**Comment by gustavormello** [comment]
Actually, you were right. It took a couple of minutes but now it's working.
