### ISSUE TITLE
Variable undefined

### ISSUE THREAD

**Issue by broferek** [thaider/Tweeki#214]
Hi,

I encountered the following exception :
```
array_shift() expects parameter 1 to be array, null given in /var/www/html/skins/Tweeki/includes/TweekiTemplate.php on line 285
```

The code in question is in the wrong order
```
$link = array_shift( $views );
$views = $this->data['view_urls'];
```
The array_shift method is called on an unitialised variable. 

Both lines must be inverted.

Thanks

**Comment by thaider** [comment]
Thanks for reporting, should be fixed in latest master. Please consider transitioning to Bootstrap 4, support will be dropped in the near future...
