### ISSUE TITLE
Mediawiki1.35.1 TOC scrollspy

### ISSUE THREAD

**Issue by michiOO** [thaider/Tweeki#228]
With Mediawiki 1.35.1, the TOC scrollspy does not work.

Updating Mediawiki improved the situation, but
I can't use this method because updating affects other extensions.

I'm guessing this is due to the version of jQuery.
Is there a better solution?

Please let me know.

**Comment by thaider** [comment]
Hi. What's the exact version of Tweeki that you're using? And could you provide a screenshot of a page with non-working TOC scrollspy? There's a known issue with special chars, do you have any (like a German umlaut) in your headings?

**Comment by michiOO** [comment]
Thanks for the answer.

The version of Tweeki is 2.0.1.

I found a new fact while making the screenshot.
I'm attaching the screenshot.

I'm Japanese, and I'm running a Japanese site.
I have a Japanese site, but it doesn't seem to work properly in Japanese.

Please check.

![Test1](https://user-images.githubusercontent.com/17515176/152684318-a5b09160-76e7-4e09-be32-a6c7ec2a22cb.PNG)
![Test2](https://user-images.githubusercontent.com/17515176/152684319-ea1ce9a5-6173-45d9-95f2-398ddb82d87e.PNG)
![テスト1](https://user-images.githubusercontent.com/17515176/152684320-92a3d822-75c3-426d-87bd-16b6e3b8fa5c.PNG)
![テスト2](https://user-images.githubusercontent.com/17515176/152684321-38e2b8b7-65b5-46f1-8b7f-7c262f20fafe.PNG)

**Comment by thaider** [comment]
Could you try if puting the following line in ```LocalSettings.php``` solves the problem:

```
$wgFragmentMode = ['html5','legacy'];
```

**Comment by michiOO** [comment]
直りました!

ありがとう。心より感謝します。


![ok](https://user-images.githubusercontent.com/17515176/152686398-8f3968dc-2a77-489c-8bce-151028ead2f1.PNG)
