### ISSUE TITLE
Logo setup

### ISSUE THREAD

**Issue by Sai05091990** [thaider/Tweeki#235]
Hello Team, 

Little confused from documentation on the logo setup for tweeki skin implemented in mediawiki. 

could you please advice on the clear settings/config on the logo part? 

Thanks

**Comment by thaider** [comment]
Hi. I suppose you want to put the logo in `navbar-brand` (in the top navigation, where the wiki's name is shown by default)? Have you read this [how-to](https://tweeki.kollabor.at/wiki/How-Tos#Logo)?

**Comment by Sai05091990** [comment]
Hello, Thanks for responding. 

There was some confusion on where to set the config ..is it in the localsetting.php or to any php file inside the skins folder ?

**Comment by Sai05091990** [comment]
Sure, Recently, i did migration of MW to k8s platform and customised the Docker file with some configuration and added few automated scripts to add the extensions and skins and recently we wanted to replace the site name with a logo as per client request.

**Comment by thaider** [comment]
So did you follow the how-to I mentioned above? What step is unclear?
