### ISSUE TITLE
How to avoid sidebar infringing on footer?

### ISSUE THREAD

**Issue by rebastion** [thaider/Tweeki#238]
Been playing around with Tweeki a lot and like it so far, kudos! There are a few things I need to iron out in order to make a final decision whether I can switch to it entirely. I love the sidebars, and with inserting random html through the special functions, I am making some progress in "abusing" the sidebar to make it look a little bit more like a Wordpress sidebar, with some widgets in it (just text and graphics for now, although I wonder if it would be possible to add more dynamic content).

What I did: Following the instructions, I added some special elements into the sidebar, that are then shown underneath the edit button (and a TOC if required), such as an info text, a little banner or an announcement.

The problem: at some point when scrolling down, the sidebar content is shoved into the footer, overlapping it (possibly because the TOC scrolls down along with the content and then pushes everything further down that is below the TOC).

Question: What do I have to do, to define the sidebar or the elements in the sidebar in a way that they will actually extend the sidebar as far as necessary? I realize that this may result in some extra white space at the end of page content once scrolled all the way down, but that's another thing.

Any tips greatly appreciated and keep up the great work, @thaider  !

**Comment by rebastion** [comment]
I thought I'd check in (making a helpless face) a week later. Can we assign, label and classify the open issues in this repo? I realize not all my probs may be priorities :D

**Comment by rebastion** [comment]
So the only way I have come to circumvent this is to just put let stuff into the sidebar, to stay sort of within a min-height that seems to exist for the main page content.... at some point though I would love to make more use of the sidebar, and once the TOC becomes very extensive, it becomes even harder.

I have attached a screenshot of a page where it is scrolled down as far as possible, please forgive the censorship, I want to  keep the project still a bit under wraps. You can see how the sidebar content is being pushed into the footer (highlighted red), this being a page that has quite a few TOC items.

![Screenshot from 2022-08-18 10-51-53](https://user-images.githubusercontent.com/13915837/185354383-28ae0998-a53d-4580-a173-0cb7d2cf1792.png)

**Comment by thaider** [comment]
should be fixed in master
