### ISSUE TITLE
Deprecated ResourceLoader

### ISSUE THREAD

**Issue by rebastion** [thaider/Tweeki#240]
Doesn't seem to break anything, but on 1.38.2 I get the following error shown in the console:
`This page is using the deprecated ResourceLoader module "skins.tweeki.styles".
[1.37] The use of the `legacy` feature with ResourceLoaderSkinModule is deprecated(T89981). More information can be found at [[mw:Manual:ResourceLoaderSkinModule]]. `

**Comment by tazzytazzy** [comment]
I've been poking around and it's related to this patch:
https://phabricator.wikimedia.org/T89981

I'm not sure how to fix it just yet.

**Comment by rebastion** [comment]
So MW has "fixed" this on their side and now skins can better chose if and what legacy resources they load, do I read this right?

**Comment by thaider** [comment]
Thanks for reporting!

**Comment by thaider** [comment]
Could you please check, if this is fixed in master? Should probably also solve most of the styling issues...

**Comment by rebastion** [comment]
is 2.0.2 identical with master right now (assuming so)? I'll upgrade all skin files to 2.0.2 later and report back

**Comment by thaider** [comment]
The change was after 2.0.2. Can you try master or do you need a tag for some reason?

**Comment by rebastion** [comment]
With master, I still get the error "This page is using the deprecated ResourceLoader module "skins.tweeki.styles". [1.37] The use of the `content-thumbnails` feature with ResourceLoaderSkinModule is deprecated. Use `content-media` instead. More nformation can be found at [[mw:Manual:ResourceLoaderSkinModule]].

**Comment by rebastion** [comment]
Show exception details is set to false; I emptied several layers of caching (memcache, varnish, mediawiki's own, my browser's) and used a fresh/blank browser, and tried on three browsers. I always see this error in the console. Retried various times. Not sure if there's any other caching I could be missing that would be so invasive?

**Comment by thaider** [comment]
My post might have been not clear enough. Did you pull latest master?

**Comment by rebastion** [comment]
yes, right after your comment yesterday

**Comment by rebastion** [comment]
Went through two more loops of emptying caches, re-uploading LocalSettings and re-uploading latest master of Tweeking, and now the error message was shortly gone at least on one browser. On others, I still see it, but not always on all pages. Might have something to do with what kind of content the skin is displaying.........

**Comment by rebastion** [comment]
No longer able to reproduce.
