### ISSUE TITLE
Bootstrap icons

### ISSUE THREAD

**Issue by rebastion** [thaider/Tweeki#242]
https://icons.getbootstrap.com/

What's the most correct way to set these up (thinking of using them instead of fontawesome maybe), like where to do I correctly put them in Tweeki's folder structure and properly include the CSS, etc.?

**Comment by thaider** [comment]
The way I would do it is to create a new extension including Bootstrap icons as a new Resource Module. This requires some knowledge of PHP and how writing an extension for MediaWiki works...
