### ISSUE TITLE
Minor design glitch on recent changes filter

### ISSUE THREAD

**Issue by rebastion** [thaider/Tweeki#243]
The recent changes page yields a minor design glitch, you can see it here in the screenshot where the bot filter is on:

![Screenshot from 2022-09-02 23-07-57](https://user-images.githubusercontent.com/13915837/188235513-cbb88df8-d190-48cc-9f2e-b9b6e32e0bbe.png)

**Comment by thaider** [comment]
I don't see the glitch here. Could you please report what versions of MediaWiki and Tweeki you're using?

**Comment by rebastion** [comment]
latest stable of Tweeki with MW 1.38.2

**Comment by thaider** [comment]
Not reproducible with MW 1.39 and latest master. Please reopen if the problem still exists in your installation.

**Comment by rebastion** [comment]
currently have no way of upgrading to latest MW until they come up with some much needed database repair tools, but i'll keep an eye out for this, it's just a minor thing really
