### ISSUE TITLE
Support Images inside of tool tips

### ISSUE THREAD

**Issue by tazzytazzy** [thaider/Tweeki#244]
I'd like to have tooltips that allowed images imbedded in.  See:
https://stackoverflow.com/questions/50737968/how-to-display-image-in-tooltip-bootstrap-4-with-php

Was hopping to get something like:
<span data-toggle="tooltip" title="<img src='http://via.placeholder.com/100x100' />">Tooltip Span</span>  

However, the <img> tag is filtered by mediawiki. Is there any known work around for this? Could this be done with a little javascript-fu?

**Comment by thaider** [comment]
It probably can be done with javascript but I can't help you here and I don't think this is going to be a Tweeki feature.
