### ISSUE TITLE
Space in File page title

### ISSUE THREAD

**Issue by rebastion** [thaider/Tweeki#245]
OK I feel almost stupid asking this after two decades of using MW, but can't seem to figure out why, in Tweeki, there is a space in the title of a file page between the "File:" and the filename... and it's not just a visual separation, there's an actual space. I mean, it still works, MW syntax is a bit lenient here, but it's not "proper", or is it?

![Screenshot from 2022-10-02 22-58-18](https://user-images.githubusercontent.com/13915837/193476050-2b29f53a-b8d4-427e-9660-bb1cc24d2784.png)

**Comment by thaider** [comment]
You're completely right, this was not an ugly hack. Anyways, MW 1.39 introduced new spans for the namespace and separator and the hack doesn't work any more. Won't be fixed for older versions. Latest master contains styles for MW's new classes.
