### ISSUE TITLE
wgTweekiSkinImagePageTOCTabs styling

### ISSUE THREAD

**Issue by rebastion** [thaider/Tweeki#246]
First I thought I was doing this wrong, but it's primarily a styling issue I think. The theme doesn't provide much styling to these tabs by default so the added value of enabling this is zero unless manual styling is applied somehow. It doesn't apply the standard bootstrap tabs styling

**Comment by thaider** [comment]
Thanks for reporting. Was never updated to Bootstrap's new syntax. Should be fixed in master.

**Comment by rebastion** [comment]
looking great
