### ISSUE TITLE
Troubles after update to MediaWiki 1.39

### ISSUE THREAD

**Issue by hra3** [thaider/Tweeki#250]
I have troubles after updating my Wikis from MediaWiki 1.35.9 to 1.39.1. The following Messages appeared if I choose the Tweeki skin:

> Deprecated: Use of User::getOption was deprecated in MediaWiki 1.35. [Called from TweekiHooks::onOutputPageBodyAttributes in /home/clients/a50ac5b7d4fdfa0993cb4503351b68e4/web/ahb/skins/Tweeki/includes/Hooks.php at line 172] in /home/clients/a50ac5b7d4fdfa0993cb4503351b68e4/web/ahb/includes/debug/MWDebug.php on line 381
> 
> Deprecated: Use of QuickTemplate::(get/html/text/haveData) with parameter `headelement` was deprecated in MediaWiki 1.39. [Called from QuickTemplate::html in /home/clients/a50ac5b7d4fdfa0993cb4503351b68e4/web/ahb/includes/skins/QuickTemplate.php at line 168] in /home/clients/a50ac5b7d4fdfa0993cb4503351b68e4/web/ahb/includes/debug/MWDebug.php on line 381

Is (or will be) there a solution or a workaround?

**Comment by thaider** [comment]
Thanks for reporting. Should be fixed in the latest release/master. Please let me know if the error messages still appear...
