### ISSUE TITLE
Allowed HTML tag <blockquote>

### ISSUE THREAD

**Issue by jlq59** [thaider/Tweeki#252]
The allowed HTML tag <blockquote> does not render the same with versions 1.2.7 and 2.0.2; version 1.2.7 renders correctly.
![image](https://user-images.githubusercontent.com/73773417/212133398-3ea3a509-68c1-475a-a64e-15c21c673186.png)
![image](https://user-images.githubusercontent.com/73773417/212133971-0af48865-1a63-49c7-8d0a-4816631908ef.png)

**Comment by jlq59** [comment]
An oversight: MediaWiki 1.35.9, 
Jean-Luc

**Comment by thaider** [comment]
Thanks for reporting. What seems to be “correct“ to you is Bootstrap v3. In Bootstrap v4 the styling looks different–and is only applied if the blockquote tag also has the class `blockquote`. [See Bootstrap's documentation](https://getbootstrap.com/docs/4.6/content/typography/#blockquotes)

**Comment by jlq59** [comment]
Merci,

Le jeu. 12 janv. 2023 à 19:39, Tobias Haider ***@***.***> a
écrit :
