### ISSUE TITLE
Linking edit button to forms when using Page Forms and Tweeki

### ISSUE THREAD

**Issue by kghbln** [thaider/Tweeki#253]
All of this is happening on MediaWiki 1.35.x: Last year, after the upgrade from version 5.4 to 5.5 of Page Forms the respective wiki had an issue with the edit buttons on Tweeki no longer linking to forms (action formedit) but linking to visual editing (veaction edit). At that point, we resolved the issue by upgrading Tweeki from version v1.2.6. In the meantime, we are using the latest version of Tweeki, v2.0.2. After upgrading to Page Forms 5.6 we are again running into the same issue. The solution here was rolling back to version 5.5.1 of Page Forms.

The developer of Page Forms [has no clue](https://www.mediawiki.org/wiki/Extension_talk:Page_Forms#Linking_edit_button_to_forms_when_using_Page_Forms_and_Tweeki) as to what may cause this and thinks it is probably Tweeki causing the problem if I interpret the answer correctly.

You may know or have an idea of what is causing this. In any case, a fix for the issue will be great since Tweeki is no longer working with the latest Page Forms, which is kind of sad.

**Comment by bmulckhu** [comment]
The issue mentioned above by kghbln is related to our website [TheaterEncyclopedie](https://theaterencyclopedie.nl/)
I'm available for any help I can provide clarifying the issue!

**Comment by thaider** [comment]
The code in it's current form depends on the order of links in `view_urls`. It uses the first item after `view` and apparently the link for editing the page with Visual Editor comes before Page Forms since recently. I'll try to look into it. To change the order of inclusion of Visual Editor and Page Forms in `Localsettings.php` doesn't change anything, I guess?

**Comment by kghbln** [comment]
Thanks a lot for your feedback!

The order of inclusion for Visual Editor and Page Forms does not make a difference. When I reported, I invoked Page Forms before Visual Editor. Now we tested with Visual Editor being invoked before Page Forms.

For Visual Editor users, the result is unchanged. For source editor users, it is now working. The default behavior for the editor shown when hitting the edit button appears to be connected to the individual user's preference. I expect the form editor to take preference when you hit the edit button if a form is connected to a page, no matter what the users do in their preferences.

**Comment by kghbln** [comment]
For [TheaterEncyclopedie](https://theaterencyclopedie.nl/) this becomes more and more some sort of a showstopper for Tweeki. It will be really cool if you could have a look into this.

**Comment by thaider** [comment]
Sorry for the late response. Should be fixed in master. Could you please test and confirm?

**Comment by kghbln** [comment]
No problem. We all have our tasks on our plates. Anyhow, you will get feedback as soon as possible.

**Comment by kghbln** [comment]
Testing took a bit longer due to summer breaks. It looks like the issue was resolved. If you do not hear from us... Thanks again for looking into this matter.
