### ISSUE TITLE
Tweeki does not show the logo.

### ISSUE THREAD

**Issue by IgorGeneralov** [thaider/Tweeki#254]
Tweeki does not show the logo in the navbar. Shows the name of the logo.
On the page MediaWiki:Tweeki-navbar-brand I'm see the logo.
I was read the instruction. How to fix this?

My wiki: http://wiki.kt-alkogol.ru

**Comment by thaider** [comment]
Please read the [documentation](https://tweeki.kollabor.at/wiki/Messages#Navbar) carefully. The content of `Mediawiki:Tweeki-navbar-brand` should be `File:Logo-WIKI.png` not `[[File:Logo-WIKI.png|class=navbar-logo]]{{SITENAME}}`.

**Comment by IgorGeneralov** [comment]
I have read the documentation.
(without brackets)
Your suggested solution doesn't work either (((((

I changed as it is written in the documentation. The result is the same.
PLS, look:
My wiki: http://wiki.kt-alkogol.ru/

**Comment by IgorGeneralov** [comment]
Thank you!
Or file or site name!
