### ISSUE TITLE
Dropdown feature of Tweeki buttons in template

### ISSUE THREAD

**Issue by GiHa** [thaider/Tweeki#256]
Hello,
I have created a Template with Tweeki-Button within.

Template:TileBtn:
```
<btn class="tile">
{{{1}}}
</btn>
```
On the wiki page I have created a button using this template.

Wiki page:
```
{{TileBtn |
Some Text
* Some Text 1
* Some Text 2
* Some Text 3
```

I get a list in a button and not a dropdown menu.

Of cause the convenient way works perfectly:
```
<btn class="tile">
Some Text
* Some Text 1
* Some Text 2
* Some Text 3
</btn>
```

Is there some workaround?

**Comment by thaider** [comment]
With the example provided, it would work if you rewrite your template as such:

```
{{#tag:btn|{{{1|}}}|class=tile}}
```

See [MediaWiki's documentation for `{{#tag:}}`](https://www.mediawiki.org/wiki/Help:Magic_words#Miscellaneous) to learn more about how that works...
