### ISSUE TITLE
customizing sidebar

### ISSUE THREAD

**Issue by MaxiMechEng** [thaider/Tweeki#258]
Hi,

is it possible to change the background colour of the buttons in the sidebar? I haven't found anything on it in the how-to section or other tutorial-like sections.
In addition to that: Is it possible to add little images into those buttons? (similar to the attached screenshot for example)
![Screenshot 2023-07-20 131015](https://github.com/thaider/Tweeki/assets/140070497/65694437-5462-4ea9-b666-124ef39e84ea)

Thanks in advance!

**Comment by rebastion** [comment]
you can style sidebar buttons with CSS, and the icons are fontawesome so those should theoretically be switchable (albeit possibly hard coded)

**Comment by MaxiMechEng** [comment]
sorry for the late response, but how do I style the sidebar buttons with CSS? I'm fairly new to the whole topic

**Comment by thaider** [comment]
You can use [Button Syntax](https://tweeki.kollabor.at/wiki/Buttons) to define sidebar items. Have a look at the [Icons](https://tweeki.kollabor.at/wiki/Buttons#Icons) section of the documentation.

If you have the line `Startseite|<i class="fa fa-home"></i> Startseite` in `MediaWiki:Tweeki-sidebar-left` the button will be shown with a home icon.

You can search for available Font Awesome icons [here](https://fontawesome.com/v5/search?o=r&m=free).

One easy way to get grey buttons would be to change `MediaWiki:Tweeki-sidebar-left-btnclass` to this: `btn btn-secondary`.

The result of the two above should look like this:

![Bildschirmfoto vom 2023-09-01 20-42-21](https://github.com/thaider/Tweeki/assets/3634883/c49b81c1-e2c7-4be2-8158-346f81c2b582)
