### ISSUE TITLE
Issue with PERSONAL - Element

### ISSUE THREAD

**Issue by GiHa** [thaider/Tweeki#260]
I am on Wiki v.1.40.0
The PERSONAL element behaves not as expected on the page https://tweeki.kollabor.at/wiki/Navigation.
It shows no "Log In"-button for anonymous visitor.

**Comment by ApaulMyLittleAirport** [comment]
![image](https://github.com/thaider/Tweeki/assets/45100828/d4ee531b-b4c1-4e4d-9c5d-b37936cd838c)

**Comment by GiHa** [comment]
You are using LOGIN-EXT there.
<img width="733" alt="grafik" src="https://github.com/thaider/Tweeki/assets/14978066/2160d678-538e-4caf-abe0-da8b8e069749">

I am speaking about PERSONAL Element.
![grafik](https://github.com/thaider/Tweeki/assets/14978066/fb2f7ff5-e326-4576-a77f-0c57563f932a)
This Log in button is not apear if user is not logged in.

**Comment by thaider** [comment]
You're completely right, thanks for the hint. Luckily, it's not a bug, it's a feature. The link to the log in form will only be shown if you make `PERSONAL` visible to anon users. It's hidden by default, so you need to set the following in LocalSettings.php:

```
$wgTweekiSkinHideAnon['PERSONAL'] = false;
```

The documentation has been amended...

**Comment by GiHa** [comment]
Yes, it works this way. Thanks.
