### ISSUE TITLE
hide sidebar automatically if it only contains an empty TOC

### ISSUE THREAD

**Issue by thaider** [thaider/Tweeki#27]

**Comment by valessiobrito** [comment]
It`s working???  @thaider

**Comment by thaider** [comment]
Hi @valessiobrito. Sorry, no, it's not working. I labeled it wontfix, because it's tricky and adds a certain unpredictability to the appearance of pages.

**Comment by valessiobrito** [comment]
@thaider thanks a lot!  Now https://libreplanet.org using Tweeki base themed.
