### ISSUE TITLE
Typed property Parser::$mOutputType must not be accessed before initialization

### ISSUE THREAD

**Issue by paladox** [thaider/Tweeki#272]
```
from /srv/mediawiki/1.41/includes/parser/Parser.php(4174)
#0 /srv/mediawiki/1.41/includes/parser/Parser.php(1581): Parser->finalizeHeadings(string, string, boolean)
#1 /srv/mediawiki/1.41/includes/parser/Parser.php(808): Parser->internalParse(string, boolean, boolean)
#2 /srv/mediawiki/1.41/skins/Tweeki/includes/Hooks.php(641): Parser->recursiveTagParse(string, boolean)
#3 /srv/mediawiki/1.41/skins/Tweeki/includes/Hooks.php(540): TweekiHooks::parseButtonLink(array, Parser, boolean)
#4 /srv/mediawiki/1.41/skins/Tweeki/includes/TweekiTemplate.php(1045): TweekiHooks::parseButtons(string, Parser, boolean)
#5 /srv/mediawiki/1.41/skins/Tweeki/includes/TweekiTemplate.php(1013): TweekiTemplate->renderCustomNavigation(array, array)
#6 /srv/mediawiki/1.41/skins/Tweeki/includes/TweekiTemplate.php(857): TweekiTemplate->buildItems(string, array, string)
#7 /srv/mediawiki/1.41/skins/Tweeki/includes/TweekiTemplate.php(829): TweekiTemplate->renderNavbarElement(string)
#8 /srv/mediawiki/1.41/skins/Tweeki/includes/TweekiTemplate.php(166): TweekiTemplate::renderNavbar(TweekiTemplate)
#9 /srv/mediawiki/1.41/skins/Tweeki/includes/TweekiTemplate.php(97): TweekiTemplate::renderPage(TweekiTemplate)
#10 /srv/mediawiki/1.41/includes/skins/SkinTemplate.php(148): TweekiTemplate->execute()
#11 /srv/mediawiki/1.41/includes/skins/SkinTemplate.php(174): SkinTemplate->generateHTML()
#12 /srv/mediawiki/1.41/includes/Output/OutputPage.php(2947): SkinTemplate->outputPage()
#13 /srv/mediawiki/1.41/includes/MediaWiki.php(978): MediaWiki\Output\OutputPage->output(boolean)
#14 /srv/mediawiki/1.41/includes/MediaWiki.php(613): MediaWiki->main()
#15 /srv/mediawiki/config/initialise/entrypoints/index.php(100): MediaWiki->run()
#16 /srv/mediawiki/config/initialise/entrypoints/index.php(95): wfIndexMain()
#17 {main}
```

**Comment by GiHa** [comment]
the same here:

Original exception: [276dbb7e9894bf910db44fd0] /wiki/index.php/Spezial:Spezialseiten Error: Typed property Parser::$mOutputType must not be accessed before initialization
Backtrace:
from /srv/wiki/includes/parser/Parser.php(4176)
#0 /srv/wiki/includes/parser/Parser.php(1581): Parser->finalizeHeadings()
#1 /srv/wiki/includes/parser/Parser.php(808): Parser->internalParse()
#2 /srv/wiki/skins/Tweeki/includes/Hooks.php(641): Parser->recursiveTagParse()
#3 /srv/wiki/skins/Tweeki/includes/Hooks.php(540): TweekiHooks::parseButtonLink()
#4 /srv/wiki/skins/Tweeki/includes/TweekiTemplate.php(1045): TweekiHooks::parseButtons()
#5 /srv/wiki/skins/Tweeki/includes/TweekiTemplate.php(1013): TweekiTemplate->renderCustomNavigation()
#6 /srv/wiki/skins/Tweeki/includes/TweekiTemplate.php(857): TweekiTemplate->buildItems()
#7 /srv/wiki/skins/Tweeki/includes/TweekiTemplate.php(829): TweekiTemplate->renderNavbarElement()
#8 /srv/wiki/skins/Tweeki/includes/TweekiTemplate.php(166): TweekiTemplate::renderNavbar()
#9 /srv/wiki/skins/Tweeki/includes/TweekiTemplate.php(97): TweekiTemplate::renderPage()
#10 /srv/wiki/includes/skins/SkinTemplate.php(148): TweekiTemplate->execute()
#11 /srv/wiki/includes/skins/SkinTemplate.php(174): SkinTemplate->generateHTML()
#12 /srv/wiki/includes/Output/OutputPage.php(2947): SkinTemplate->outputPage()
#13 /srv/wiki/includes/MediaWiki.php(978): MediaWiki\Output\OutputPage->output()
#14 /srv/wiki/includes/MediaWiki.php(613): MediaWiki->main()
#15 /srv/wiki/index.php(50): MediaWiki->run()
#16 /srv/wiki/index.php(46): wfIndexMain()
#17 {main}

Wiki v.1.41
Tweeki the latest version version

**Comment by daniel-centore** [comment]
I was able to fix this by adding the following line immediately after both of the `$parser = ` lines in `TweekiTemplate.php`:

```php
$parser->setOutputType(Parser::OT_HTML);
```
