### ISSUE TITLE
about using table and pagination

### ISSUE THREAD

**Issue by vlasvlasvlas** [thaider/Tweeki#55]
Hi, i couldnt find any way to include a paginated table into tweeki wikimedia. 

do you know any way i can include a paginated grid/table using your template? thanks!

i mean using this kindo of bootstrap table:

http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#basic-toolbar-table

but just pagination.....

pleeease

**Comment by vlasvlasvlas** [comment]
i mean using this kindo of bootstrap table:

http://wenzhixin.net.cn/p/bootstrap-table/docs/examples.html#basic-toolbar-table

**Comment by thaider** [comment]
Hi. Could you elaborate a bit what you are trying to achieve? If you want to use the Bootstrap Table plugin you've been linking to you would have to write your own extension to load the css and javascript files. You can find instructions on how to do that here: 

https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader

**Comment by vlasvlasvlas** [comment]
ok thanks! . btw do you know any already made paginated table plugin for wikimedia?
