### ISSUE TITLE
How can i add discussion in all pages?

### ISSUE THREAD

**Issue by serralex** [thaider/Tweeki#63]
I want to have the discussion(or talk page) in every page. I've already checked the documentation 
and I have already added the corresponding navigational element in $wgTweekiSkinNavigationalElements but not working. Any idea?

(https://cloud.githubusercontent.com/assets/19570597/15538529/1271fab8-227d-11e6-83cf-ef056e742502.png)

Thanks for the work. Is a nice and fully skin

**Comment by thaider** [comment]
Depending on where you would like the link to the talk page to appear you would have to add the string `TALK` into the according message (it should be documented [here](http://tweeki.thai-land.at/wiki/Messages) but I just saw that it is broken resp. not updated – will fix this asap)...

E.g. if you want to have the link in the right sidebar, you would have to edit `MediaWiki:Tweeki-sidebar-right` and change it's content to `TALK,EDIT-EXT,TOC` (assuming you want to keep the existing entries). If you want it in the subnavigation you would have to edit `MediaWiki:Tweeki-subnav` and so on...

Note: To achieve this it's not necessary to change the configuration files. Also you should avoid modifying the extension files and instead add configuration options in `LocalSettings.php`.

**Comment by serralex** [comment]
Thanks thaider 👍  :)
