### ISSUE TITLE
How can I put an item of Personal Tools outside the dropdown menu?

### ISSUE THREAD

**Issue by takigous** [thaider/Tweeki#66]
Let's say I want to put the "Preferences" item outside the personal tools and add it in header instead. Is that possible?

**Comment by thaider** [comment]
Depending on your level of knowledge of PHP and CSS, there are several ways to achieve this, e.g. you can:
* simply add `Special:Preferences|Preferences` to `MediaWiki:Tweeki-navbar-right` or wherever you would like it to appear (and use custom stylings to hide `#pt-preferences` in the dropdown)
* overwrite `PERSONAL-EXT`/`PERSONAL` using the `$wgTweekiSkinNavigationalElements` configuration option in `LocalSettings.php` or your own extension (this is not very well documented yet) – just have a look at how they're built in `Tweeki.skin.php` and copy & modify the code
* likewise create your own `PREFERENCES` navigational element
