### ISSUE TITLE
MediaWiki internal error

### ISSUE THREAD

**Issue by EdwardBlack** [thaider/Tweeki#68]
Just tried this theme. When I go to https://mydomain.wiki/User:USERNAME I'll get an error.

`Original exception: [9828c280166598e8330b09d0] /User:XAPE MWException from line 553 of /var/www/nautic.wiki/html/includes/Html.php: HTML attribute tooltip-params can not contain a list of values
Backtrace:
#0 /var/www/nautic.wiki/html/includes/Html.php(296): Html::expandAttributes(array)
#1 /var/www/nautic.wiki/html/includes/Html.php(211): Html::openElement(string, array)
#2 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(661): Html::rawElement(string, array, string)
#3 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(694): TweekiHooks::makeLink(array, array)
#4 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(574): TweekiHooks::makeListItem(array)
#5 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(549): TweekiHooks::buildDropdownMenu(array, string)
#6 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(502): TweekiHooks::buildDropdown(array)
#7 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(870): TweekiHooks::renderButtons(array, array)
#8 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(712): TweekiTemplate->buildItems(string, array, string)
#9 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(691): TweekiTemplate->renderNavbarElement(string)
#10 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(249): TweekiTemplate->renderNavbar()
#11 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(199): TweekiTemplate->renderPage(TweekiTemplate)
#12 /var/www/nautic.wiki/html/includes/skins/SkinTemplate.php(248): TweekiTemplate->execute()
#13 /var/www/nautic.wiki/html/includes/OutputPage.php(2324): SkinTemplate->outputPage()
#14 /var/www/nautic.wiki/html/includes/MediaWiki.php(753): OutputPage->output()
#15 /var/www/nautic.wiki/html/includes/MediaWiki.php(519): MediaWiki->main()
#16 /var/www/nautic.wiki/html/index.php(43): MediaWiki->run()
#17 {main}

Exception caught inside exception handler: [9828c280166598e8330b09d0] /User:XAPE MWException from line 553 of /var/www/nautic.wiki/html/includes/Html.php: HTML attribute tooltip-params can not contain a list of values
Backtrace:
#0 /var/www/nautic.wiki/html/includes/Html.php(296): Html::expandAttributes(array)
#1 /var/www/nautic.wiki/html/includes/Html.php(211): Html::openElement(string, array)
#2 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(661): Html::rawElement(string, array, string)
#3 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(694): TweekiHooks::makeLink(array, array)
#4 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(574): TweekiHooks::makeListItem(array)
#5 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(549): TweekiHooks::buildDropdownMenu(array, string)
#6 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.hooks.php(502): TweekiHooks::buildDropdown(array)
#7 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(870): TweekiHooks::renderButtons(array, array)
#8 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(712): TweekiTemplate->buildItems(string, array, string)
#9 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(691): TweekiTemplate->renderNavbarElement(string)
#10 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(249): TweekiTemplate->renderNavbar()
#11 /var/www/nautic.wiki/html/skins/Tweeki/Tweeki.skin.php(199): TweekiTemplate->renderPage(TweekiTemplate)
#12 /var/www/nautic.wiki/html/includes/skins/SkinTemplate.php(248): TweekiTemplate->execute()
#13 /var/www/nautic.wiki/html/includes/OutputPage.php(2324): SkinTemplate->outputPage()
#14 /var/www/nautic.wiki/html/includes/exception/MWException.php(204): OutputPage->output()
#15 /var/www/nautic.wiki/html/includes/exception/MWException.php(244): MWException->reportHTML()
#16 /var/www/nautic.wiki/html/includes/exception/MWExceptionHandler.php(69): MWException->report()
#17 /var/www/nautic.wiki/html/includes/exception/MWExceptionHandler.php(180): MWExceptionHandler::report(MWException)
#18 /var/www/nautic.wiki/html/includes/MediaWiki.php(528): MWExceptionHandler::handleException(MWException)
#19 /var/www/nautic.wiki/html/index.php(43): MediaWiki->run()
#20 {main}`

**Comment by thaider** [comment]
Thanks for the report. Could you please let me know if you customized any of the messages connected to navigation (e.g. `MediaWiki:Tweeki-navbar-left` or `MediaWiki:Tweeki-footer`) and what their content is.

**Comment by EdwardBlack** [comment]
No, didn't change anything. Out of the box Media Wiki with no changes and installed the theme.

**Comment by EdwardBlack** [comment]
(also it's working with all the other themes I tested)

**Comment by thaider** [comment]
What version of MediaWiki are you using and have you installed any extensions?

**Comment by EdwardBlack** [comment]
No extensions, Version 1.27.0

**Comment by thaider** [comment]
I could reproduce the error and I think I found fix – could you please confirm.
