### ISSUE TITLE
Left sidebar

### ISSUE THREAD

**Issue by BrunoRobert** [thaider/Tweeki#73]
How can I use the left sidebar. Is it possible to move the toc there?

Bruno

**Comment by thaider** [comment]
Hi. Just edit `MediaWiki:tweeki-sidebar-left` and add `TOC` as its content. If there is content it will automatically be shown. To avoid conflicts delete `TOC` from `MediaWiki:tweeki-sidebar-right`

**Comment by BrunoRobert** [comment]
Thx, That's easy ;)

Bruno
