### ISSUE TITLE
Plaintext or plain buttons in the sidebar

### ISSUE THREAD

**Issue by jennkei** [thaider/Tweeki#74]
Thanks for the skin! I like it...but I'm having some trouble with the Sidebar.

I don't like buttons or things to be collapsed by default so I can't use SIDEBAR. I know it's possible to expand them all by default ([remixthecommons](http://wiki.remixthecommons.org/index.php/MediaWiki:Sidebar)) but I don't like how uneven that looks either, not to mention I have no idea how to do that.

I did manage to find out a way to put plaintext links, but now I need something to differentiate categories of links. Bold, non-linked text, even a plain button would do (for some reason I don't like the blue ones..) Apart from adding a bunch of Special Elements to the LocalSettings.php, which isn't the most convenient for a Wiki, is there any way of doing this?

Documentation states to "..add your own custom items using button markup." but button markup doesn't seem to be working for me. I'm trying `<btn>Wiki Admin</btn>` and it renders on the page, but not on the sidebar.  Page I'm working on - http://granblue.x10host.com/wiki/Mediawiki:Tweeki-sidebar-left/edit

**Comment by thaider** [comment]
Hi. Sorry, if the documentation doesn't really elaborate on this. What it should say is “...using button markup without the `<btn>` tags”. So if you just use „Wiki Admin“, as you did with the two other links on the page, you should be fine.

As for the styling: You can define the classes for every link seperately as the third argument of a button definition or you can change the default for all buttons in the sidebar editing `Mediawiki:Tweeki-sidebar-left-btnclass`.

As for the remixthecommons trick: they've simply put this line into `MediaWiki:Common.css`:

```css
#sidebar-left ul.dropdown-menu {display:block;max-width:260px;}
```

If you want to group your links, use custom classes and some css in `MediaWiki:Common.css` (e.g. have a class `.category-start` and apply it to all links that should be seperated from the previous ones, than insert something like `.category-start { margin-top:20px }` to `MediaWiki:Common.css`). You could also have a special class for headlines (and make it bold or something). Unfortunately, it is currently not possible to have non-link elements in the navigational section. You would have to use Special Elements for that. If you have a suggestion on how to implement it markup-wise, let me know. Maybe I'll find the time to look into it...

**Comment by jennkei** [comment]
Ahh. Eh, using just 'Wiki Admin' would have given me a button, though.

Thanks, I hadn't considered CSS, for some reason. I tried tinkering with it but gave up in the end and just pasted the default display for Mediawiki:Sidebar in. Does kind of kill the responsiveness but hopefully MobileFrontEnd will work for that..

Speaking of responsive, though, it's nice that the left sidebar drops down, but it covers the Footer as a result. Not sure if you've noticed? Either way, just a tiny detail.

**Comment by thaider** [comment]
This is quite interesting, what you did here, because I can't reproduce it on my own instances. You have some links in your `MediaWiki:Tweeki-sidebar-left` before the `SIDEBAR` navigational element, but they're not shown. Did you change anything else? How did you install Tweeki? Did you clone with git or did you download a release?

Also, could you send a screenshot of the sidebar covering the footer, that would help clarify this issue. Thank you!

**Comment by jennkei** [comment]
Haha Tobias, I modified your php code and pasted the normal sidebar call in. :) Don't worry about my site, I'm happy with how it currently looks.

And I think I was dreaming when I posted that, cos it looks absolutely fine on mobile. (left sidebar doesn't show) Haha. http://i.imgur.com/WO6cAd6.png This is what I was talking about, but it only happens with small resized windows on Desktop mode so it is absolutely not an issue, please ignore that!
