### ISSUE TITLE
Catlinks not showing?

### ISSUE THREAD

**Issue by jennkei** [thaider/Tweeki#76]
Hmm, at first I thought it was just a quirk of the skin, but recently I've started to find this would be a useful feature to have, so I tried to figure out how to add it in, only to realise it's apparently already added in? ._. I see <?php $this->html( 'catlinks' ); ?> already in the template file..but it's not showing up on my pages.

Example page which is in the Items category: http://granblue.x10host.com/wiki/Qinglong_Seal

Works (kinda, formatting is a bit wonky) if I change skin to Monobook or something else, though.

**Comment by thaider** [comment]
Tweeki hides some of MediaWiki's features to have a clean interface. In the case of the category links it's only done via the stylesheet. You had the right intuition that you can overwrite it in you `MediaWiki:Common.css`, just that `catlinks` is an `id` and not a `class`, so you would need to use the following line:

```
#catlinks {display:block;}
```
