### ISSUE TITLE
Usage of logo

### ISSUE THREAD

**Issue by pixuenan** [thaider/Tweeki#77]
Hi thaider,

I tried to use Tweeki skin with my mediawiki 1.26.2. I really likes this skin but I encountered with a problem about the logo. On the original website without Tweeki skin there was a logo at the top left corner. But there is no logo after I use the Tweeki skin, the "'LOGO => 'self::renderLogo'" option is enabled at the $wgTweekiSkinSpecialElements array. 

When I check the code of the renderLogo function in the Tweeki.skin.php file, I found it use Xml format, is this the reason why the logo is absent? Or is there other solution for the display of logo?

**Comment by thaider** [comment]
`LOGO` is a [Navigational Element](http://tweeki.thai-land.at/wiki/Navigation#Navigational_Elements) that is not used by default. If you want to use it, you can place it in any of the [Navigational Sections](http://tweeki.thai-land.at/wiki/Navigation#Navigational_Sections).

Example: If you want your Logo to appear in the left sidebar, edit `MediaWiki:Tweeki-sidebar-left` and change it's content to contain `LOGO`.

I just found out, that it's not working in `MediaWiki:Tweeki-navbar-brand`, however, and created a new issue for that – #78 If you want an image to appear in `navbar-brand` as a workaround you can just upload a file as you would normally do and set `MediaWiki:Tweeki-navbar-brand` to the name of the file page (e.g. `File:MyLogo.png`) [see here](http://tweeki.thai-land.at/wiki/Messages#Navbar)
