### ISSUE TITLE
Parameter 1 expected to be a reference

### ISSUE THREAD

**Issue by davidlimjh** [thaider/Tweeki#83]
I get an error while trying to use this theme with the latest version of mediawiki 1.28 thats running on the latest version of XAMPP with PHP 7.1

`Warning: Parameter 1 to TweekiHooks::HeadlineFix() expected to be a reference, value given in F:\xampp\htdocs\wiki\includes\Hooks.php on line 195`

Is there anything i've missed out?

**Comment by davidlimjh** [comment]
Seems like this is an issue with version 7.1 of PHP. When I reverted to PHP 5.6 the skin worked.

**Comment by thaider** [comment]
Thanks for reporting. I didn't have the possibility to test with PHP 7 so far. Quite possible that there are also other things that would need to be fixed...

**Comment by thaider** [comment]
The warning might be connected with this ticket in phabricator: https://phabricator.wikimedia.org/T153505
