### ISSUE TITLE
Pipes in ParserFunction breaks tweeki-sidebar links

### ISSUE THREAD

**Issue by nickwynja** [thaider/Tweeki#87]
Hi Tobias, thanks for making Tweeki.

I'm attempting to use [Extension:PageInCat](https://www.mediawiki.org/wiki/Extension:PageInCat) to make a dynamic tweeki-sidebar-left which changes based on the page you're on. The sidebar seems to be choking on any ParserFunctions which use a `|` to separate arguments.

My goal is for the following to render a list of Components when I'm on a page with a category of "component" and to be blank if not.

```
{{#ifpageincategory: Components | {{#ask:[[Category:Components]]}} | }}
```
The output of that is a link `{{#ifpageincategory: Components` with an `href` of `invalid-title:{{#ifeq:%20True`.

The same approach fails with other simple ParserFunctions. `{{#if: 0 | yes | no }}` renders `yes` with an `href` of `invalid-title:{{#if:%200`.

ParserFunctions that _do not_ contain a `|` do work properly. `{{#time: Y-m-d }}` returns the proper date with a valid link.

All of the above ParserFunctions work properly in the contents of the page so the functions are valid, they just aren't being rendered properly in Tweeki's sidebar.

Are you able to suggest any potential workarounds for this? Thanks again.

**Comment by thaider** [comment]
Hi.

One solution would be to use a custom navigational element. I added an example on the [how-to page](http://tweeki.thai-land.at/wiki/How-Tos#Show_or_hide_navigational_elements_depending_e.g._on_category). Please report, if this works for you. Thanks.

**Comment by nickwynja** [comment]
This worked great! Thanks for the help.
