### ISSUE TITLE
Tweeki navbar and Categories questions

### ISSUE THREAD

**Issue by m-fonseca** [thaider/Tweeki#88]
Hello,  I have 2 questions about categories with Tweeki.

1.  Is there a way to put category entries in the navbar without showing the word category?  E.g. If I edit Tweeki-navbar-left, and have Food,\*Cateogry:Cheese,\*Category:Beans,  This works except shows the word Category.  If I try Food,\*[[Category:Cheese|Cheese]],\*[[Caegory:Beans|Beans]] .  This does not work.

2.  Is there a way to dynamically build a menu entry, to show pages that belong to a category?  E.g.  Currently I use the categorytree extension, and could doe something like `<categorytree mode=all>Food</categorytree>`  and it would list all the pages.  Is there a way to adopt this to Tweeki navbar, or do something like it?

Thanks!

**Comment by thaider** [comment]
Hi, thanks for your questions. Please note, that in the navigational sections you can always use Tweeki's [Button syntax](http://tweeki.thai-land.at/wiki/Buttons). Their general specification is `target|text|class`, so you could write `Food,*Category:Cheese|Cheese,*Category:Beans|Beans` (without brackets!) to achieve (1).

In the documentation for [Dropdown Buttons](http://tweeki.thai-land.at/wiki/Buttons#Dropdown_Buttons) you'll find an example for a Semantic Dropdown that you can also use for the navigation. So for (2) you could just add `Food,*{{#ask:[[Category:Food]]}}` to your navbar.

**Comment by m-fonseca** [comment]
Thanks!  That helped a bunch.
