### ISSUE TITLE
MediaWiki internal error. 

### ISSUE THREAD

**Issue by kghbln** [thaider/Tweeki#90]
**Setup**
- MediaWiki 	1.29.0-rc.0 (37c22fc) 23:03, 22 June 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.31-MariaDB-1~jessie
- Tweeki	0.1.4 (c116315) 21:30, 12 April 2017

**Issue 1**
MediaWiki internal error. Original exception: [1a67b3ca77b25ee19d533def] /wiki/Sp%C3%A9cial:Pr%C3%A9f%C3%A9rences MWException from line 539 of /../w/includes/Html.php: HTML attribute data can not contain a list of values

**Backtrace**
```
#0 /../w/includes/Html.php(299): Html::expandAttributes(array)
#1 /../w/includes/Html.php(210): Html::openElement(string, array)
#2 /../w/skins/Tweeki/Tweeki.hooks.php(728): Html::rawElement(string, array, string)
#3 /../w/skins/Tweeki/Tweeki.hooks.php(747): TweekiHooks::makeLink(array, array)
#4 /../w/skins/Tweeki/Tweeki.hooks.php(631): TweekiHooks::makeListItem(array)
#5 /../w/skins/Tweeki/Tweeki.hooks.php(606): TweekiHooks::buildDropdownMenu(array, string)
#6 /../w/skins/Tweeki/Tweeki.hooks.php(559): TweekiHooks::buildDropdown(array)
#7 /../w/skins/Tweeki/Tweeki.skin.php(923): TweekiHooks::renderButtons(array, array)
#8 /../w/skins/Tweeki/Tweeki.skin.php(765): TweekiTemplate->buildItems(string, array, string)
#9 /../w/skins/Tweeki/Tweeki.skin.php(744): TweekiTemplate->renderNavbarElement(string)
#10 /../w/skins/Tweeki/Tweeki.skin.php(259): TweekiTemplate->renderNavbar()
#11 [internal function]: TweekiTemplate->renderPage(TweekiTemplate)
#12 /../w/skins/Tweeki/Tweeki.skin.php(199): call_user_func_array(string, array)
#13 /../w/includes/skins/SkinTemplate.php(251): TweekiTemplate->execute()
#14 /../w/includes/OutputPage.php(2441): SkinTemplate->outputPage()
#15 /../w/includes/MediaWiki.php(869): OutputPage->output(boolean)
#16 /../w/includes/MediaWiki.php(881): MediaWiki->{closure}()
#17 /../w/includes/MediaWiki.php(523): MediaWiki->main()
#18 /../w/index.php(43): MediaWiki->run()
#19 {main}
```

**Issue 2**
Exception caught inside exception handler: [1a67b3ca77b25ee19d533def] /wiki/Sp%C3%A9cial:Pr%C3%A9f%C3%A9rences MWException from line 539 of /../w/includes/Html.php: HTML attribute data can not contain a list of values

**Backtrace**
```
#0 /../w/includes/Html.php(299): Html::expandAttributes(array)
#1 /../w/includes/Html.php(210): Html::openElement(string, array)
#2 /../w/skins/Tweeki/Tweeki.hooks.php(728): Html::rawElement(string, array, string)
#3 /../w/skins/Tweeki/Tweeki.hooks.php(747): TweekiHooks::makeLink(array, array)
#4 /../w/skins/Tweeki/Tweeki.hooks.php(631): TweekiHooks::makeListItem(array)
#5 /../w/skins/Tweeki/Tweeki.hooks.php(606): TweekiHooks::buildDropdownMenu(array, string)
#6 /../w/skins/Tweeki/Tweeki.hooks.php(559): TweekiHooks::buildDropdown(array)
#7 /../w/skins/Tweeki/Tweeki.skin.php(923): TweekiHooks::renderButtons(array, array)
#8 /../w/skins/Tweeki/Tweeki.skin.php(765): TweekiTemplate->buildItems(string, array, string)
#9 /../w/skins/Tweeki/Tweeki.skin.php(744): TweekiTemplate->renderNavbarElement(string)
#10 /../w/skins/Tweeki/Tweeki.skin.php(259): TweekiTemplate->renderNavbar()
#11 [internal function]: TweekiTemplate->renderPage(TweekiTemplate)
#12 /../w/skins/Tweeki/Tweeki.skin.php(199): call_user_func_array(string, array)
#13 /../w/includes/skins/SkinTemplate.php(251): TweekiTemplate->execute()
#14 /../w/includes/OutputPage.php(2441): SkinTemplate->outputPage()
#15 /../w/includes/exception/MWException.php(174): OutputPage->output()
#16 /../w/includes/exception/MWException.php(220): MWException->reportHTML()
#17 /../w/includes/exception/MWExceptionHandler.php(73): MWException->report()
#18 /../w/includes/exception/MWExceptionHandler.php(141): MWExceptionHandler::report(MWException)
#19 /../w/includes/MediaWiki.php(551): MWExceptionHandler::handleException(MWException)
#20 /../w/index.php(43): MediaWiki->run()
#21 {main}
```

**Comment by kghbln** [comment]
Note that I am acutally using 1.0.4. The version seems to be defined incorrectly for the respective tag.

**Comment by thaider** [comment]
I just made a test installation with MediaWiki 1.29.0-rc.1 (929f8dc) 01:59, 8. Jul. 2017 and couldn't reproduce the problem. Did you customize the navbars and if so could you provide their contents?

**Comment by kghbln** [comment]
> I just made a test installation with MediaWiki 1.29.0-rc.1 (929f8dc) 01:59, 8. Jul. 2017 and couldn't reproduce the problem. Did you customize the navbars and if so could you provide their contents?

Admittedly I just installed Tweeki without doing further configuration. It is a [public wiki](https://sandbox.semantic-mediawiki.org/wiki/Main_Page)

**Comment by thaider** [comment]
Could you point me to a page where the error's showing up? The [main page](https://sandbox.semantic-mediawiki.org/wiki/Main_Page?useskin=tweeki) seems to work fine with Tweeki or am I missing something?

**Comment by kghbln** [comment]
> Tweeki or am I missing something?

You have to use Tweeki though. The error appears on every page as soon as you try to [use Tweeki.](https://sandbox.semantic-mediawiki.org/w/index.php?title=Main_Page&useskin=tweeki)

**Comment by thaider** [comment]
I did use Tweeki. Looks fine to me:

![Screenshot](http://tweeki.thai-land.at/w/images/3/35/Screenshot_tweeki.png)

**Comment by kghbln** [comment]
> I did use Tweeki. Looks fine to me:

We are getting closer. The error seems to appear only for logged in users when. If I am not logged in I indeed do not get the issue either.

**Comment by thaider** [comment]
I could imagine it to be a conflict with one of the many extensions that you've installed. Could you please insert this line

`if( isset( $attrs['data'] ) && is_array( $attrs['data'] ) ) die( var_dump( $attrs ) );`

at line 693 of `Tweeki.hooks.php`, just before

`$html = Html::rawElement( isset( $attrs['href'] ) ? 'a' : $options['link-fallback'], $attrs, $html );`

and post the output.

**Comment by thaider** [comment]
Hi @kghbln, I think I found the culprit. It's the Echo extension which is using new LinkRenderer syntax not yet supported by Tweeki. I've been aware of the changes (see #69) but didn't find the time to do it. Please report if the quick fix solved your problem, i.e. if the error messages disappear. I fear the appearance of Echo in the dropdown in the navigation might be something of a disaster, I haven't tried it before.

**Comment by kghbln** [comment]
@thaider Thanks a lot for your effort. Indeed the change you authored made the issue go away. Thanks a lot. Besides, Echo is a total disaster for other skins, too. It was basically completely refactored twice recently with heaps of breaking changes. It is still not working nicely but that's another story.
