### ISSUE TITLE
css error

### ISSUE THREAD

**Issue by dimage** [thaider/Tweeki#92]
![default](https://user-images.githubusercontent.com/10204962/27997256-5339a1c2-64fd-11e7-9783-35cc0f08e4d4.png)
How to fix css?

`[[Файл:Mercury-svh-0.png|750px|обрамить|центр|Рис. 1. Схема организации работы пользователя с подсистемой Меркурий.СВХ]]

[[Файл:Mercury-svh-0.png|750px|безрамки|центр|Рис. 1. Схема организации работы пользователя с подсистемой Меркурий.СВХ]]
`
Image with frame and without a frame, width 750

**Comment by thaider** [comment]
Hi. This is not an issue of Tweeki. See [MediaWiki's documentation for images](https://www.mediawiki.org/wiki/Help:Images#Size_and_frame):

> An image with frame always ignores the size specification, the original image will be reduced if it exceeds the maximum size defined in user preferences.

I would suggest using the second version (безрамки) and putting it in a wrapping div that you can style to your liking. Or you could even mimic центр behaviour by using something like this (you could put this code in a template if needed frequently):

```
<div class="thumb center">
<div class="thumbinner" style="width:752px;">
[[Файл:Mercury-svh-0.png|750px|безрамки|Рис. 1. Схема организации работы пользователя с подсистемой Меркурий.СВХ|class=thumbimage]]
<div class="thumbcaption">Рис. 1. Схема организации работы пользователя с подсистемой Меркурий.СВХ</div>
</div>
</div>
```

**Comment by dimage** [comment]
thanks

**Comment by dimage** [comment]
Tell me please how to add a banner to the internal page in Tweeki-sidebar-right ?

**Comment by dimage** [comment]
I will be very grateful

**Comment by thaider** [comment]
I'm not sure, if I get you right, but I see two options. Both require some understanding of PHP and CSS.

* [Define a custom page layout](http://tweeki.thai-land.at/wiki/Configuration_Options#Page_Layout) using `$wgTweekiSkinPageRenderer`
* [Create a special navigational element](http://tweeki.thai-land.at/wiki/Configuration_Options#Special_Elements) that produces arbitrary output. Documentation isn't very versatile on this, but you would have to put something like this in `LocalSettings.php` or in your own extension:

```
$wgTweekiSkinSpecialElements['BANNER'] = 'banner';

function banner( $skin ) {
	echo '<div class="banner">Your banner HTML</div>';
	}
```

Then add the text `BANNER` to your `MediaWiki:Tweeki-navbar-right`.

**Comment by dimage** [comment]
Thank you! You gave me direction for thoughts
