### ISSUE TITLE
Drop-down menues are always expanded

### ISSUE THREAD

**Issue by kghbln** [thaider/Tweeki#93]
### Setup and configuration

- MediaWiki | 1.29.0-rc.1 (929f8dc)01:59, 8 July 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.31-MariaDB-1~jessie
- Tweeki | 1.0.4 (80299b9) 22:53, 8 July 2017

### Issue
![bildschirmfoto vom 2017-07-10 10-29-33](https://user-images.githubusercontent.com/1104078/28009212-e5630e28-655a-11e7-876a-e75959ae691f.png)

**Comment by thaider** [comment]
You've got some custom CSS either defined by yourself or by some extension that reads

```
.navbar ul {
    display: inline;
    white-space: nowrap;
}
```

This conflicts with Bootstrap's `navbar` class. Either you get rid of it or you redefine Bootstrap's display styles with higher specificity like this:

```
.navbar ul .dropdown-menu {
    display: none;
}
.navbar ul .open .dropdown-menu {
    display: block;
}
```

And Echo's not even a complete mess, that's good to see ;)

**Comment by kghbln** [comment]
@thaider Ouch, my mistake. I a sorry for wasting your time and thank you for the pointer!. Somebody added CSS stuff from enwikipedia to common.css. Now that this is at vector.css things are indeed cool. Echo is indeed not a complete mess but still the display may be improved somehow. ;)
