### ISSUE TITLE
Display conflict with Headertabs

### ISSUE THREAD

**Issue by m-art-in** [thaider/Tweeki#96]
After installing Tweeki all pages with `<headertabs/>` have a little issue. The aren't displayed anymore as expected:
![grafik](https://user-images.githubusercontent.com/15324884/29024992-e9fee684-7b74-11e7-905e-2a56c7bc32c1.png)
They are too small to display the labels. Behavior is still fine....

Any help? Seems to be a css issue

**Comment by thaider** [comment]
Hey. I'm sorry, but I don't have the resources to look into this. Patches are always welcome if you succeed to solve the issue. If you don't rely on linking to specific tabs you could consider using Bootstrap's tabs which are supported by Tweeki (see the [documentation](http://tweeki.thai-land.at/wiki/Tabs)).
