### ISSUE TITLE
Fresh installation of mediawiki and Twiki setup looks bad by default.

### ISSUE THREAD

**Issue by lidiamartinez** [thaider/Tweeki#98]
For new users of wikimedia this is quite confusing, the look is bad and there are some css problems that we can't solve at first glance. Wouldn't it be supposed to work right out of the box?

![sin titulo](https://user-images.githubusercontent.com/9552809/30737594-8061dd76-9f87-11e7-97fc-4a219262f068.png)

**Comment by lidiamartinez** [comment]
Oh. It's all in spanish, sorry for that.

**Comment by thaider** [comment]
Hi. Thanks for your report. Could you please indicate the versions of MediaWiki and Tweeki that you're using? And please post the contents of `MediaWiki:Tweeki-navbar-brand` and `MediaWiki:Tweeki-navbar-left` – those are customized, right?

**Comment by lidiamartinez** [comment]
I'm using the latest version from two weeks ago exactly. I'm sorry I stopped using this theme and I deleted it. :-(  I didn't customize anything. As I said, I just installed it.

**Comment by Omaniac** [comment]
I have exactly the same issue... MW 1.30 SWM 2.5.5, latest version of Tweeki. The entire installation was fresh, no modifications to any MediaWiki:Tweeki-xxx-xxx file.

![screenshot from 2018-02-16 18 08 18](https://user-images.githubusercontent.com/36544615/36319849-8f04739e-1344-11e8-97ac-6fb34e7ebc39.png)

**Comment by thaider** [comment]
I just tried to reproduce the problem but didn't succeed, everything looks quite normal:

![screenshot_fresh_install](https://user-images.githubusercontent.com/3634883/36344937-3e998712-1422-11e8-8577-1e77c7fcd58b.png)

Is there a chance that one of you could provide a publicly accessible installation where this bug exists?

**Comment by thaider** [comment]
I thought it could have something to do with your wikis being non-English but that doesn't seem to be the problem...

**Comment by thaider** [comment]
It seems that some css files don't get loaded for some reason I cannot imagine...

**Comment by Omaniac** [comment]
I have a online environment where everything works just fine, where I use an ISP. They run MariaDB and php 5.6.

The environment I'm having trouble with is on a local host. I run Elementaryos, and Firefox browser. Have given 777 permission on every folder under /var/www

Can it be any php.ini stuff?

What I dont understand is why the text in the upper left i shown. On my ISP environment this is not the case. I see Lidia has the same in her screenshot.

One thing... I installed Tweeki manually. Just copied the files to /skins and enabled it manually in LocalSettings.php. The same on the ISP site.

These Mediawiki:Tweeki-xxx-xxx files... are they present by default? Should they be? How many of them?

Perhaps we can share screen / remote desktop so you can examine my local environment? It's pretty much a fresh and clean install of Elementaryos with apache, mysql and php, with mw, smw and some other nice extensions.

**Comment by Omaniac** [comment]
Ahhh... finally solved :) My mistake. After I had copied Tweeki to /skins, I made a mistake by dragging another folder called mediawiki, and didn't notice where I dropped it. When I went through the folders, I noticed a folder called /skins/tweeki/mediawiki and assumed this was the folder I dropped there by mistake. But now I see that the mediawiki folder is a part of Tweeki - so, I'm so sorry. Now it works like a charm :)

![screenshot from 2018-02-18 18 36 26](https://user-images.githubusercontent.com/36544615/36354866-b038a944-14da-11e8-86d7-ffa78604b2f8.png)

**Comment by thaider** [comment]
Cool, that's great! Answering to your question about the Mediawiki:Tweeki-xxx „files“. If you want to dig deeper you can have a look at MediaWiki's [help page about system messages](https://www.mediawiki.org/wiki/Help:System_message). They've actually been introduced to make internationalization and localization/customization possible and easy. The reason why Tweeki uses systems messages for configuration is, that you don't have to mess with LocalSettings.php and can make changes on the site (i.e. in the database). There are hardcoded defaults for all the messages and you can overwrite them by actually creating the respective page and changing its content.
