### ISSUE TITLE
Pipe links (or corresponding) needed for navigation links

### ISSUE THREAD

**Issue by jonatanskogsfors** [thaider/Tweeki#99]
When linking to special pages on a media wiki it is quite common to use piped links (see https://www.mediawiki.org/wiki/Help:Links#Internal_links) in order to avoid writing the full namespace.

Is this possible in a Tweeki navigation bar?
The link "Special:RecentChanges" is not as catchy as just "Recent changes".

**Comment by thaider** [comment]
Yes, this is possible. Have a look at Tweeki's [Button Syntax](https://tweeki.thai-land.at/wiki/Buttons) and especially it's [Specifications](https://tweeki.thai-land.at/wiki/Buttons#Specifications). In the navigation you could just write `Special:RecentChanges|Recent changes` (without brackets).
